/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
export const getTemplate = () => ({
  name: "Hello World",
  description: "Basic client Java service sample",
  sources: [
    {
      location: "/template-hello-world/service.java.template",
      action: "generate",
      rename: "{{javaPackageName}}/{{javaClassName}}.java",
    },
  ],
  parameters: [],
  order: 0,
});
