/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
import * as generateUtils from "service-generate/template/generateUtils";
import * as parameterUtils from "service-generate/template/parameterUtils";

export function generate(model, parameters) {
    model = JSON.parse(model).model;
    let templateSources = getTemplate(parameters).sources;
    parameterUtils.process(model, parameters)
    return generateUtils.generateFiles(model, parameters, templateSources);
};

export function getTemplate(parameters) {
    return {
        name: "Application - Events - Java",
        description: "Process-trigger glue-code (Java listeners) from the intent model",
        extension: "model",
        sources: [
            {
                location: "/template-application-events-java/events/Trigger.java.template",
                action: "generate",
                rename: "gen/events/{{process}}Trigger.java",
                engine: "velocity",
                collection: "triggers"
            },
            {
                location: "/template-application-events-java/project.json.mjs",
                action: "generate",
                rename: "project.json",
                engine: "javascript",
            }
        ],
        parameters: []
    };
};
