/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
import * as generateUtils from "service-generate/template/generateUtils";
import { sanitizeJavaIdentifier } from "service-generate/template/parameterUtils";

export function generate(model, parameters) {
    // The .glue file is { triggers: [...], resolvers: [...] } - no entity model. generateUtils
    // filters model.entities up front, so give it an empty list; the gen package root comes from the
    // glue file's base name (same as the full-stack gen folder).
    const glue = JSON.parse(model);
    glue.entities = glue.entities || [];
    parameters.javaGenFolderName = sanitizeJavaIdentifier(parameters.genFolderName);
    let templateSources = getTemplate(parameters).sources;
    return generateUtils.generateFiles(glue, parameters, templateSources);
};

export function getTemplate(parameters) {
    return {
        name: "Application - Glue Code - Java",
        description: "Process glue-code (Java listeners + decision resolvers) generated from the intent .glue file",
        extension: "glue",
        sources: [
            {
                location: "/template-application-events-java/events/Trigger.java.template",
                action: "generate",
                rename: "gen/events/{{javaGenFolderName}}/{{process}}Trigger.java",
                engine: "velocity",
                collection: "triggers"
            },
            {
                location: "/template-application-events-java/events/Resolver.java.template",
                action: "generate",
                rename: "gen/events/{{javaGenFolderName}}/{{handler}}.java",
                engine: "velocity",
                collection: "resolvers"
            },
            {
                location: "/template-application-events-java/events/SetField.java.template",
                action: "generate",
                rename: "gen/events/{{javaGenFolderName}}/{{className}}.java",
                engine: "velocity",
                collection: "setters"
            },
            {
                location: "/template-application-events-java/events/FieldLoader.java.template",
                action: "generate",
                rename: "gen/events/{{javaGenFolderName}}/{{handler}}.java",
                engine: "velocity",
                collection: "fieldLoaders"
            },
            {
                location: "/template-application-events-java/events/TimerLoader.java.template",
                action: "generate",
                rename: "gen/events/{{javaGenFolderName}}/{{handler}}.java",
                engine: "velocity",
                collection: "timerLoaders"
            },
            {
                location: "/template-application-events-java/events/Wait.java.template",
                action: "generate",
                rename: "gen/events/{{javaGenFolderName}}/{{className}}Wait.java",
                engine: "velocity",
                collection: "waits"
            },
            {
                location: "/template-application-events-java/events/Abort.java.template",
                action: "generate",
                rename: "gen/events/{{javaGenFolderName}}/{{process}}Abort.java",
                engine: "velocity",
                collection: "aborts"
            },
            {
                location: "/template-application-events-java/events/Writer.java.template",
                action: "generate",
                rename: "gen/events/{{javaGenFolderName}}/{{className}}.java",
                engine: "velocity",
                collection: "writers"
            },
            {
                location: "/template-application-events-java/events/Notification.java.template",
                action: "generate",
                rename: "gen/events/{{javaGenFolderName}}/{{className}}Notification.java",
                engine: "velocity",
                collection: "notifications"
            },
            {
                location: "/template-application-events-java/events/Job.java.template",
                action: "generate",
                rename: "gen/events/{{javaGenFolderName}}/{{className}}Job.java",
                engine: "velocity",
                collection: "schedules"
            },
            {
                location: "/template-application-events-java/events/Integration.java.template",
                action: "generate",
                rename: "gen/events/{{javaGenFolderName}}/{{className}}Integration.java",
                engine: "velocity",
                collection: "integrations"
            },
            {
                location: "/template-application-events-java/events/Webhook.java.template",
                action: "generate",
                rename: "gen/events/{{javaGenFolderName}}/{{className}}Webhook.java",
                engine: "velocity",
                collection: "inbound"
            },
            {
                location: "/template-application-events-java/events/Rollup.java.template",
                action: "generate",
                rename: "gen/events/{{javaGenFolderName}}/{{className}}.java",
                engine: "velocity",
                collection: "rollups"
            },
            {
                location: "/template-application-events-java/events/Expansion.java.template",
                action: "generate",
                rename: "gen/events/{{javaGenFolderName}}/{{className}}.java",
                engine: "velocity",
                collection: "expansions"
            },
            {
                location: "/template-application-events-java/events/PrintFeeder.java.template",
                action: "generate",
                rename: "gen/events/{{javaGenFolderName}}/{{className}}PrintFeeder.java",
                engine: "velocity",
                collection: "printFeeders"
            },
            {
                location: "/template-application-events-java/events/Snapshot.java.template",
                action: "generate",
                rename: "gen/events/{{javaGenFolderName}}/{{master}}SnapshotGenerator.java",
                engine: "velocity",
                collection: "snapshots"
            },
            {
                location: "/template-application-events-java/events/Numbering.java.template",
                action: "generate",
                rename: "gen/events/{{javaGenFolderName}}/{{entity}}NumberStamp.java",
                engine: "velocity",
                collection: "numbering"
            },
            {
                location: "/template-application-events-java/events/SettlementOnPayment.java.template",
                action: "generate",
                rename: "gen/events/{{javaGenFolderName}}/{{name}}OnPayment.java",
                engine: "velocity",
                collection: "settlements"
            },
            {
                location: "/template-application-events-java/events/SettlementOnInvoice.java.template",
                action: "generate",
                rename: "gen/events/{{javaGenFolderName}}/{{name}}OnInvoice.java",
                engine: "velocity",
                collection: "settlements"
            },
            {
                location: "/template-application-events-java/events/Generate.java.template",
                action: "generate",
                rename: "gen/events/{{javaGenFolderName}}/{{className}}Generate.java",
                engine: "velocity",
                collection: "generates"
            },
            {
                location: "/template-application-events-java/events/Transition.java.template",
                action: "generate",
                rename: "gen/events/{{javaGenFolderName}}/{{className}}Transition.java",
                engine: "velocity",
                collection: "transitions"
            },
            {
                location: "/template-application-events-java/events/Posting.java.template",
                action: "generate",
                rename: "gen/events/{{javaGenFolderName}}/{{className}}Posting.java",
                engine: "velocity",
                collection: "postings"
            },
            {
                location: "/template-application-events-java/events/Posts.java.template",
                action: "generate",
                rename: "gen/events/{{javaGenFolderName}}/{{className}}Post.java",
                engine: "velocity",
                collection: "posts"
            },
            {
                location: "/template-application-events-java/project.json.mjs",
                action: "generate",
                rename: "project.json",
                engine: "javascript",
            }
        ],
        parameters: []
    };
};
