/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */

export function getTemplate(parameters) {
    return {
        name: "Application - DAO - Java",
        description: "Application with DAO (Java)",
        extension: "model",
        sources: [
            {
                location: "/template-application-dao-java/data/Repository.java.template",
                action: "generate",
                rename: "gen/{{javaGenFolderName}}/data/{{javaPerspectiveName}}/{{name}}Repository.java",
                engine: "velocity",
                collection: "daoModels"
            },
            {
                location: "/template-application-dao-java/data/Entity.java.template",
                action: "generate",
                rename: "gen/{{javaGenFolderName}}/data/{{javaPerspectiveName}}/{{name}}Entity.java",
                engine: "velocity",
                collection: "daoModels"
            },
            {
                location: "/template-application-dao-java/data/entity.extensionpoint.template",
                action: "generate",
                rename: "gen/{{javaGenFolderName}}/data/{{javaPerspectiveName}}/{{name}}.extensionpoint",
                engine: "velocity",
                collection: "daoModels"
            },
            {
                location: "/template-application-dao-java/project.json.mjs",
                action: "generate",
                rename: "project.json",
                engine: "javascript",
            }
        ],
        parameters: [
            {
                name: "tablePrefix",
                label: "Table Prefix",
                placeholder: "Table prefix",
                required: false
            },
            {
                name: "dataSource",
                label: "Data Source",
                placeholder: "Data Source (DefaultDB)",
                required: false
            }
        ]
    };
};
