/*
 * Copyright (c) 2010-2026 Eclipse Dirigible contributors
 *
 * All rights reserved. This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: Eclipse Dirigible contributors SPDX-License-Identifier: EPL-2.0
 */
package org.eclipse.dirigible.components.intent.parser;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.eclipse.dirigible.components.intent.model.IntentModel;
import org.junit.jupiter.api.Test;

/**
 * The parse-time half of a schedule's relative moment: a staleness sweep parses, and every way the
 * comparison could not actually be made is an authoring error rather than a query that silently
 * never matches.
 */
class ScheduleMomentIntentTest {

    private static final String ENTITIES = """
            name: provisioning
            entities:
              - name: TenantApplication
                audit: true
                fields:
                  - { name: id,                 type: integer, primaryKey: true, generated: true }
                  - { name: provisioningStatus, type: string, length: 40 }
                  - { name: sentOn,             type: date }
                  - { name: changedAt,          type: timestamp }
                  - { name: attempts,           type: integer }
            """;

    @Test
    void theStalenessSweepParses() {
        IntentModel model = IntentParser.parse(ENTITIES + """
                schedules:
                  - name: stuckProvisioning
                    cron: "0 */5 * * * ?"
                    entity: TenantApplication
                    where:
                      - { field: provisioningStatus, op: eq, value: Provisioning }
                      - { field: changedAt,          op: lt, value: "CURRENT_TIMESTAMP-PT30M" }
                    notify: { to: ops@example.com, subject: "Stuck", body: "It may need an operator." }
                """);

        assertEquals("CURRENT_TIMESTAMP-PT30M", model.getSchedules()
                                                     .get(0)
                                                     .getWhere()
                                                     .get(1)
                                                     .getValue());
    }

    @Test
    void anAuditColumnMayCarryTheSweep() {
        // UpdatedAt is generated by `audit: true`, so it is not among the declared fields - the check
        // must leave it alone rather than call the archetypal sweep an error.
        IntentParser.parse(ENTITIES + """
                schedules:
                  - name: untouched
                    cron: "0 */5 * * * ?"
                    entity: TenantApplication
                    where:
                      - { field: updatedAt, op: lt, value: "CURRENT_TIMESTAMP-PT30M" }
                    notify: { to: ops@example.com, subject: "Untouched", body: "No change in 30 minutes." }
                """);
    }

    @Test
    void aTimeOffsetOnADateFieldFailsTheParse() {
        assertFails("""
                      - { field: sentOn, op: lt, value: "CURRENT_DATE-PT30M" }
                """, "a date takes a date-only amount");
    }

    @Test
    void anOffsetThatIsNotAnIso8601DurationFailsTheParse() {
        assertFails("""
                      - { field: changedAt, op: lt, value: "CURRENT_TIMESTAMP-30M" }
                """, "not a single ISO-8601 duration");
    }

    @Test
    void twoOffsetsOnOneTokenFailTheParse() {
        assertFails("""
                      - { field: changedAt, op: lt, value: "CURRENT_TIMESTAMP-P7D-P1D" }
                """, "not a single ISO-8601 duration");
    }

    @Test
    void aMomentOnANonTemporalFieldFailsTheParse() {
        assertFails("""
                      - { field: attempts, op: lt, value: "CURRENT_TIMESTAMP-PT30M" }
                """, "compares the non-temporal field [attempts]");
    }

    @Test
    void aMomentOfTheOtherShapeThanTheFieldFailsTheParse() {
        assertFails("""
                      - { field: sentOn, op: lt, value: "CURRENT_TIMESTAMP-P7D" }
                """, "use CURRENT_DATE");
        assertFails("""
                      - { field: changedAt, op: lt, value: CURRENT_DATE }
                """, "use CURRENT_TIMESTAMP");
    }

    private static void assertFails(String condition, String expected) {
        String intent = ENTITIES + """
                schedules:
                  - name: sweep
                    cron: "0 */5 * * * ?"
                    entity: TenantApplication
                    where:
                """ + condition + """
                    notify: { to: ops@example.com, subject: "Sweep", body: "Body." }
                """;
        IntentValidationException failure = assertThrows(IntentValidationException.class, () -> IntentParser.parse(intent));
        assertTrue(failure.getMessage()
                          .contains(expected),
                failure.getMessage());
    }
}
