/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
import * as daoTemplateManager from "template-application-dao-v2/template/template";
import * as generateUtils from "service-generate/template/generateUtils";
import * as parameterUtils from "service-generate/template/parameterUtils";

export function generate(model, parameters) {
    model = JSON.parse(model).model;
    let templateSources = getTemplate(parameters).sources;
    parameterUtils.process(model, parameters)
    return generateUtils.generateFiles(model, parameters, templateSources);
};

export function getTemplate(parameters) {
    let daoTemplate = daoTemplateManager.getTemplate(parameters);

    let templateSources = [{
        location: "/template-application-feed-v2/feed/entityFeedSynchronizer.ts.template",
        action: "generate",
        rename: "gen/{{genFolderName}}/feed/{{perspectiveName}}/{{name}}FeedSynchronizer.ts",
        engine: "velocity",
        collection: "feedModels"
    }, {
        location: "/template-application-feed-v2/feed/entityFeed.job.template",
        action: "generate",
        rename: "gen/{{genFolderName}}/feed/{{perspectiveName}}/{{name}}Feed.job",
        engine: "velocity",
        collection: "feedModels"
    }];
    templateSources = templateSources.concat(daoTemplate.sources);

    let templateParameters = [];
    templateParameters = templateParameters.concat(daoTemplate.parameters);

    return {
        name: "Application - Feed - v2",
        description: "Application with Feed Entities",
        extension: "model",
        sources: templateSources,
        parameters: templateParameters
    };
};