# https://opentelemetry.io/docs/collector/configuration/

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 5s
    send_batch_size: 10000

extensions:
  health_check: {}

exporters:
  debug:
    # supported: basic, normal and detailed
    verbosity: normal
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:9090"
  opensearch:
    logs_index: otel
    http:
      endpoint: "http://opensearch:9200"
      tls:
        insecure: true
  otlphttp/loki:
    endpoint: "http://loki:3100/otlp"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [ batch ]
      exporters: [otlp/jaeger, debug]
    metrics:
      receivers: [otlp]
      processors: [ batch ]
      exporters: [prometheus, debug]
    logs:
      receivers: [otlp]
      processors: [ batch ]
      exporters: [otlphttp/loki, debug]
