/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
export const getTemplate = () => ({
  name: "Scheduled Job (Java)",
  description: "Scheduled Job with a client Java handler",
  sources: [
    {
      location: "/template-job/handler.java.template",
      action: "generate",
      rename: "{{javaPackageName}}/{{javaClassName}}.java",
    },
  ],
  parameters: [],
  order: 50,
});
