/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */

/*
 * The ADMINISTRATION surface - one deliberately PLAIN page per MODULE (every non-projection,
 * non-report entity as a flat table + flat record editor over the power REST controllers),
 * registered on `application-admin-perspectives` (the Administration shell, ADMINISTRATOR-gated).
 * The entity metadata is baked in by the `adminModel` collection case (the generation pipeline's
 * ModelGenerator), which
 * renders each source ONCE per module with `adminEntitiesJson` in the context.
 */
export const getSources = () => [
    {
        location: "/template-application-ui-harmonia-java/ui/admin/admin-index.html.template",
        action: "generate",
        engine: "velocity",
        rename: "gen/{{genFolderName}}/admin/index.html",
        collection: "adminModel"
    },
    {
        location: "/template-application-ui-harmonia-java/ui/admin/admin-perspective.js.template",
        action: "generate",
        engine: "velocity",
        rename: "gen/{{genFolderName}}/perspectives/admin/perspective.js",
        collection: "adminModel"
    },
    {
        location: "/template-application-ui-harmonia-java/ui/admin/admin-perspective.extension.template",
        action: "generate",
        engine: "velocity",
        rename: "gen/{{genFolderName}}/perspectives/admin/perspective.extension",
        collection: "adminModel"
    }
];
