/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */

/*
 * Calendar view type — Harmonia SPA variant.
 *
 * A PRIMARY entity declared with `view: calendar` is emitted by EdmIntentGenerator with layoutType
 * MANAGE_CALENDAR plus the calendar* metadata (calendarStartProperty / calendarEndProperty /
 * calendarTitleProperty / calendarColorProperty / calendarInitialView). It renders as a full-page
 * Harmonia x-h-calendar: the entity's records become events, positioned by the date/datetime field.
 *
 * The calendar reuses the SAME generated REST controller (fetch) and the SAME shared create/edit form
 * as a manage entity - no new backend, no new form:
 *   /<Entity>            -> the calendar page (browse)
 *   /<Entity>/create     -> the shared form (create; opened on date-click)
 *   /<Entity>/{id}/edit  -> the shared form (edit; opened on event-click)
 *
 * Collection: uiCalendarModels = layoutType === "MANAGE_CALENDAR" && type === "PRIMARY".
 */
export function getSources(parameters) {
    const collection = "uiCalendarModels";
    return [
        // The calendar page + its view fragment.
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/calendar/calendar-page.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/js/components/pages/{{perspectiveName}}/{{name}}CalendarPage.js",
            collection
        },
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/calendar/calendar-view.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/views/{{perspectiveName}}/{{name}}-calendar.html",
            collection
        },
        // Reuse the shared manage create/edit form (page + view) so date-click / event-click can open it.
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/manage/form-page.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/js/components/pages/{{perspectiveName}}/{{name}}FormPage.js",
            collection
        },
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/manage/form-view.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/views/{{perspectiveName}}/{{name}}-form.html",
            collection
        }
    ];
};
