/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */

/*
 * Document (header-items) view type — Harmonia SPA variant.
 *
 * A master that owns a composition child whose name ends in "Item" (SalesInvoice ->
 * SalesInvoiceItem) is emitted by EdmIntentGenerator with layoutType MANAGE_DOCUMENT and a
 * `documentItemsEntity` pointing at that child. Such a master renders as a full-page document:
 *   - a header form (the master's own scalar + relationship fields, minus the aggregate totals),
 *   - an inline-editable line-items table (the *Item child, per-row server-side create/update/delete),
 *   - a right-aligned totals footer (the fields flagged `aggregate` — read-only calculated values; the
 *     header is re-fetched after every item change so server-side calculated fields refresh).
 *
 * Routing (see ui/shell/index.html.template, MANAGE_DOCUMENT branch):
 *   /<Master>            -> the reused manage list page (browse documents)
 *   /<Master>/create     -> the document editor (create mode)
 *   /<Master>/{id}/edit  -> the document editor (edit mode; items enabled)
 *
 * The line-items entity stays a MANAGE_DETAILS DEPENDENT (handled by masterDetail.js): its
 * registration (App.registerDetail) supplies the inline table's columns + editColumns + controller,
 * so the document page never enumerates the child's fields at generation time. Any OTHER composition
 * child of the master renders as an ordinary detail panel below the totals.
 *
 * Collection: uiDocumentModels = layoutType === "MANAGE_DOCUMENT" && type === "PRIMARY".
 */
export function getSources(parameters) {
    const collection = "uiDocumentModels";
    return [
        // Browse list — reuse the manage list page/view (its New/Edit buttons route to /create and
        // /{id}/edit, which the shell maps to the document editor for MANAGE_DOCUMENT entities).
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/manage/list-page.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/js/components/pages/{{perspectiveName}}/{{name}}ManageListPage.js",
            collection
        },
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/manage/list-view.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/views/{{perspectiveName}}/{{name}}-manage-list.html",
            collection
        },
        // The document editor — header form + inline items table + totals footer.
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/document/document-page.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/js/components/pages/{{perspectiveName}}/{{name}}DocumentPage.js",
            collection
        },
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/document/document-view.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/views/{{perspectiveName}}/{{name}}-document.html",
            collection
        }
    ];
};
