/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */

/*
 * List view (LIST layout, PRIMARY entities) — Harmonia SPA variant.
 *
 * Unlike the Angular module (one iframe perspective per entity, registered via
 * .extension + view.js + controller.js), the Harmonia runtime is a single SPA:
 * each entity contributes two generated artefacts that the shell wires together —
 *   1. an Alpine.data page component (the list state machine on the fetch client),
 *   2. a Harmonia view fragment rendered into #app on navigation.
 * The <template x-route> declaration itself is emitted once into index.html (the
 * aggregate shell loops the model), so there is no separate per-entity route file.
 *
 * Collection `uiListModels` = entities with layoutType === "LIST" && type === "PRIMARY".
 * Velocity model vars available per entity: $name, $properties[], $property.dataName,
 * $property.widgetType, $property.widgetIsMajor, $property.dataAutoIncrement,
 * $perspectiveName, $projectName, ${tprefix}, $hasProcess, ${primaryKeysString}.
 */
export function getSources(parameters) {
    return [
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/list/page.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/js/components/pages/{{perspectiveName}}/{{name}}ListPage.js",
            collection: "uiListModels"
        },
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/list/view.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/views/{{perspectiveName}}/{{name}}-list.html",
            collection: "uiListModels"
        }
    ];
};
