/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */

/*
 * Manage view (MANAGE layout, PRIMARY entities) — Harmonia SPA variant.
 *
 * In the Angular module a MANAGE perspective is a list table plus inline
 * create/edit/delete dialogs. The SPA splits that into routed pages (the athena
 * pattern): per MANAGE entity it emits
 *   1. a CRUD list page component + view (New / Edit / Delete + delete-confirm),
 *   2. a SHARED create/edit form page component + view, built on baseFormPage so
 *      422 ValidationError causes map onto per-field errors.
 *
 * The shell wires three routes per entity (see ui/shell/index.html.template):
 *   /{name}             -> {name}-manage-list.html   (x-data {name}ManageListPage)
 *   /{name}/create      -> {name}-form.html          (x-data {name}FormPage)
 *   /{name}/{id}/edit   -> {name}-form.html          (same view; page reads :id)
 *
 * Collection `uiManageModels` = layoutType === "MANAGE" && type === "PRIMARY".
 * Per-entity Velocity vars additionally include, for relationship DROPDOWNs:
 * $property.widgetDropdownControllerUrl, $property.widgetDropDownKey,
 * $property.widgetDropDownValue, $property.widgetDropDownMultiSelect; plus the
 * form flags $property.isRequiredProperty / isCalculatedProperty / isReadOnlyProperty /
 * auditType / dataAutoIncrement, and the entity-level $dataName / $primaryKeysString.
 */
export function getSources(parameters) {
    return [
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/manage/list-page.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/js/components/pages/{{perspectiveName}}/{{name}}ManageListPage.js",
            collection: "uiManageModels"
        },
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/manage/list-view.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/views/{{perspectiveName}}/{{name}}-manage-list.html",
            collection: "uiManageModels"
        },
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/manage/form-page.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/js/components/pages/{{perspectiveName}}/{{name}}FormPage.js",
            collection: "uiManageModels"
        },
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/manage/form-view.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/views/{{perspectiveName}}/{{name}}-form.html",
            collection: "uiManageModels"
        }
    ];
};
