/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */

/*
 * Master-detail view types — Harmonia SPA variant.
 *
 * Master entities (LIST_MASTER / MANAGE_MASTER, PRIMARY) get a master page at /<Master>:
 * an x-h-split with the master record list on the left and, for the selected master, its
 * editable form plus one detail panel per dependent entity on the right.
 *
 * Detail entities (LIST_DETAILS / MANAGE_DETAILS, DEPENDENT) do NOT get their own list
 * route; instead each emits:
 *   - a registration (<Detail>.detail.js) that calls App.registerDetail(<masterEntity>, {...})
 *     so the master page can render a generic detailPanel for it (decoupled — masters never
 *     enumerate their details at generation time), and
 *   - a routed create/edit form (reusing the manage form templates) at /<Detail>/create and
 *     /<Detail>/{id}/edit, which the detail panel navigates to with the FK + returnTo preset.
 *
 * The detail list is filtered to its master via the generated controller's
 * `?<masterEntityId>=<id>` query (masterEntityId = the FK property; masterEntity = the master
 * entity name — both set by parameterUtils for MANAGE_DETAILS/LIST_DETAILS entities).
 */
export function getSources(parameters) {
    // A master gets: the master page (list + detail orchestration) AND the manage form
    // (reused for its own routed create/edit at /<Master>/create and /<Master>/{id}/edit).
    const masterPage = (collection) => ([
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/master/master-page.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/js/components/pages/{{perspectiveName}}/{{name}}MasterPage.js",
            collection
        },
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/master/master-view.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/views/{{perspectiveName}}/{{name}}-master.html",
            collection
        },
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/manage/form-page.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/js/components/pages/{{perspectiveName}}/{{name}}FormPage.js",
            collection
        },
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/manage/form-view.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/views/{{perspectiveName}}/{{name}}-form.html",
            collection
        }
    ]);

    const detail = (collection) => ([
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/master/detail-register.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/js/components/pages/{{perspectiveName}}/{{name}}.detail.js",
            collection
        },
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/manage/form-page.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/js/components/pages/{{perspectiveName}}/{{name}}FormPage.js",
            collection
        },
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/manage/form-view.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/views/{{perspectiveName}}/{{name}}-form.html",
            collection
        }
    ]);

    return [
        ...masterPage("uiManageMasterModels"),
        ...masterPage("uiListMasterModels"),
        ...detail("uiManageDetailsModels"),
        ...detail("uiListDetailsModels")
    ];
};
