/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */

/*
 * The personal (my) surface pages - generated only for entities with a personal owner relation
 * (or the scope inherited from their composition parent). Roots get a list page and a shell
 * perspective (contributed to `application-personal-perspectives`, aggregated by the My Shell);
 * every personal entity gets a form page, reached from the list or from a parent's child panel
 * (an embedded calendar for detailCalendar children, a table otherwise). The pages talk to the
 * scoped <Entity>MyController only - sensitive fields never reach them.
 */
export const getSources = () => [
    {
        location: "/template-application-ui-harmonia-java/ui/my/my-list-page.js.template",
        action: "generate",
        engine: "velocity",
        rename: "gen/{{genFolderName}}/js/components/pages/my/{{name}}MyListPage.js",
        collection: "personalRootModels"
    },
    {
        location: "/template-application-ui-harmonia-java/ui/my/my-list-view.html.template",
        action: "generate",
        engine: "velocity",
        rename: "gen/{{genFolderName}}/views/my/{{name}}-list.html",
        collection: "personalRootModels"
    },
    {
        location: "/template-application-ui-harmonia-java/ui/my/my-form-page.js.template",
        action: "generate",
        engine: "velocity",
        rename: "gen/{{genFolderName}}/js/components/pages/my/{{name}}MyFormPage.js",
        collection: "personalFormModels"
    },
    {
        location: "/template-application-ui-harmonia-java/ui/my/my-form-view.html.template",
        action: "generate",
        engine: "velocity",
        rename: "gen/{{genFolderName}}/views/my/{{name}}-form.html",
        collection: "personalFormModels"
    },
    {
        // Personal DOCUMENT layout: a MANAGE_DOCUMENT personal root renders as a document (header form
        // + inline items table + status pill + totals) scoped to its MyController, instead of the plain
        // my-form above (which excludes document roots).
        location: "/template-application-ui-harmonia-java/ui/my/my-document-page.js.template",
        action: "generate",
        engine: "velocity",
        rename: "gen/{{genFolderName}}/js/components/pages/my/{{name}}MyDocumentPage.js",
        collection: "personalDocumentModels"
    },
    {
        location: "/template-application-ui-harmonia-java/ui/my/my-document-view.html.template",
        action: "generate",
        engine: "velocity",
        rename: "gen/{{genFolderName}}/views/my/{{name}}-document.html",
        collection: "personalDocumentModels"
    },
    {
        location: "/template-application-ui-harmonia-java/ui/my/my-perspective.js.template",
        action: "generate",
        engine: "velocity",
        rename: "gen/{{genFolderName}}/perspectives/my/{{name}}/perspective.js",
        collection: "personalRootModels"
    },
    {
        location: "/template-application-ui-harmonia-java/ui/my/my-perspective.extension.template",
        action: "generate",
        engine: "velocity",
        rename: "gen/{{genFolderName}}/perspectives/my/{{name}}/perspective.extension",
        collection: "personalRootModels"
    }
];
