/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */

/*
 * Navigation - contributes each top-level entity to the shared application shell (the platform
 * dashboard) as a perspective registered to the `application-perspectives` extension point, grouped
 * by the entity's navigation group (`groupId`, from the intent `group:`). This is ADDITIVE: the
 * project's own standalone Harmonia SPA (assembled in ui/shell/index.html) is unchanged; these
 * extensions only make the same entities ALSO appear, grouped, in the one shared shell so the user
 * does not jump between per-project apps.
 *
 * The navigation GROUPS themselves are defined once elsewhere (a dedicated navigation-groups project
 * that exports getPerspectiveGroup() for each group id), so a group shared by several projects is not
 * declared multiple times (the shell drops duplicate ids).
 *
 * One perspective per top-level entity across every primary layout plus settings, so reference data
 * (settings) can sit as first-class grouped entries (e.g. UoM/Country/Currency under "Master Data").
 */
const PERSPECTIVE_COLLECTIONS = [
    "uiListModels",
    "uiManageModels",
    "uiManageMasterModels",
    "uiListMasterModels",
    "uiDocumentModels",
    "uiSettingModels"
];

export const getSources = () => PERSPECTIVE_COLLECTIONS.flatMap(collection => ([
    {
        location: "/template-application-ui-harmonia-java/ui/perspective/perspective.js.template",
        action: "generate",
        engine: "velocity",
        rename: "gen/{{genFolderName}}/perspectives/{{name}}/perspective.js",
        collection
    },
    {
        location: "/template-application-ui-harmonia-java/ui/perspective/perspective.extension.template",
        action: "generate",
        engine: "velocity",
        rename: "gen/{{genFolderName}}/perspectives/{{name}}/perspective.extension",
        collection
    }
]));
