/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */

/*
 * Navigation — in the Angular module this emits a perspective-group .extension per
 * navigation node (consumed by the IDE/dashboard shell). In the Harmonia SPA there
 * is no extension-point registry: the sidebar nav is data inside appShell's
 * `nav` array, assembled in index.html from the model.
 *
 * TODO (Phase 1/2): emit a generated `js/nav.js` (or a JSON include) holding the
 * { route, label, icon } entries per navigation node, which appShell.js reads
 * instead of its hard-coded demo array. For now the skeleton folds nav into the
 * aggregate index.html (see ui/shell/index.html.template), so this collector is a
 * no-op placeholder that keeps the aggregator wiring honest.
 */
export const getSources = () => ([]);
