/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */

/*
 * The PARTNER surface pages - the external-partner (Customer/Supplier) mirror of the personal (my)
 * surface, generated only for entities with a `partner: true` owner relation (or the scope inherited
 * from their composition parent). Roots get a list page and a shell perspective (contributed to
 * `application-partner-perspectives`, aggregated by the Partner shell - disjoint from the My shell);
 * every partner entity gets a form page, reached from the list or from a parent's child panel. The
 * pages talk to the scoped <Entity>PartnerController only - sensitive fields never reach them.
 */
export const getSources = () => [
    {
        location: "/template-application-ui-harmonia-java/ui/partner/partner-list-page.js.template",
        action: "generate",
        engine: "velocity",
        rename: "gen/{{genFolderName}}/js/components/pages/partner/{{name}}PartnerListPage.js",
        collection: "partnerRootModels"
    },
    {
        location: "/template-application-ui-harmonia-java/ui/partner/partner-list-view.html.template",
        action: "generate",
        engine: "velocity",
        rename: "gen/{{genFolderName}}/views/partner/{{name}}-list.html",
        collection: "partnerRootModels"
    },
    {
        location: "/template-application-ui-harmonia-java/ui/partner/partner-form-page.js.template",
        action: "generate",
        engine: "velocity",
        rename: "gen/{{genFolderName}}/js/components/pages/partner/{{name}}PartnerFormPage.js",
        collection: "partnerFormModels"
    },
    {
        location: "/template-application-ui-harmonia-java/ui/partner/partner-form-view.html.template",
        action: "generate",
        engine: "velocity",
        rename: "gen/{{genFolderName}}/views/partner/{{name}}-form.html",
        collection: "partnerFormModels"
    },
    {
        // Partner DOCUMENT layout: a MANAGE_DOCUMENT partner root renders as a document (header form
        // + inline items + status pill + totals) scoped to its PartnerController, instead of the plain
        // partner-form above (which excludes document roots).
        location: "/template-application-ui-harmonia-java/ui/partner/partner-document-page.js.template",
        action: "generate",
        engine: "velocity",
        rename: "gen/{{genFolderName}}/js/components/pages/partner/{{name}}PartnerDocumentPage.js",
        collection: "partnerDocumentModels"
    },
    {
        location: "/template-application-ui-harmonia-java/ui/partner/partner-document-view.html.template",
        action: "generate",
        engine: "velocity",
        rename: "gen/{{genFolderName}}/views/partner/{{name}}-document.html",
        collection: "partnerDocumentModels"
    },
    {
        location: "/template-application-ui-harmonia-java/ui/partner/partner-perspective.js.template",
        action: "generate",
        engine: "velocity",
        rename: "gen/{{genFolderName}}/perspectives/partner/{{name}}/perspective.js",
        collection: "partnerRootModels"
    },
    {
        location: "/template-application-ui-harmonia-java/ui/partner/partner-perspective.extension.template",
        action: "generate",
        engine: "velocity",
        rename: "gen/{{genFolderName}}/perspectives/partner/{{name}}/perspective.extension",
        collection: "partnerRootModels"
    }
];
