/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */

/*
 * Related-records registers — the reverse of an incoming to-one association.
 *
 * An entity that declares `relatedEntities` (records REFERENCING it) emits one registration file,
 * <Entity>.related.js, calling App.registerRelated for each register. Its form, document and master
 * pages then render one read-only relatedPanel per registered entry — read from the runtime registry
 * rather than baked into every page template, so the metadata is emitted once per entity.
 *
 * Collection `uiRelatedModels` = entities with a non-empty `relatedEntities`.
 */
export function getSources(parameters) {
    return [
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/related/related-register.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/js/components/pages/{{perspectiveName}}/{{name}}.related.js",
            collection: "uiRelatedModels"
        }
    ];
};
