/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */

/*
 * Report view types — Harmonia SPA variant. Report entities (type REPORT) run server-side through
 * the generated Java report controller (template-application-rest-java's reportFileEntity:
 * GET / -> rows as column->value maps, POST /search filter, POST /export CSV). The report
 * perspective is "Reports", so the page apiPath resolves to <restBase>/reports/<Name>Controller.
 *
 *   - REPORT_TABLE  (uiReportTableModels) -> a data table.
 *   - REPORT_BAR/LINE/PIE/DOUGHNUT/POLARAREA/RADAR (uiReportChartModels) -> a native Harmonia
 *     x-h-chart-* chart, labelled by the report's primary-key column with one series per other column.
 */
export function getSources(parameters) {
    return [
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/report/table-page.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/js/components/pages/{{perspectiveName}}/{{name}}ReportPage.js",
            collection: "uiReportTableModels"
        },
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/report/table-view.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/views/{{perspectiveName}}/{{name}}-report.html",
            collection: "uiReportTableModels"
        },
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/report/chart-page.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/js/components/pages/{{perspectiveName}}/{{name}}ReportPage.js",
            collection: "uiReportChartModels"
        },
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/report/chart-view.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/views/{{perspectiveName}}/{{name}}-report.html",
            collection: "uiReportChartModels"
        }
    ];
};
