/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */

/*
 * Sources for a standalone .report — Harmonia variant. The backend (reportFileEntity Repository +
 * Controller + default roles + project.json) is identical to the AngularJS report-file template
 * (it is framework-neutral Java); only the UI differs — a self-contained Alpine.js + Harmonia page
 * (index.html + report.js) under gen/<genFolder>/reports/<name>/, in place of the AngularJS
 * perspective. The page queries the generated Java report controller directly.
 */
export function getSources() {
    return [
        // The report's label catalog: the report tId/label, one entry per column, and the KPI
        // widget's tile label when present — under the '<Name>-report' translation prefix, consumed
        // by the shell's i18n service (sidebar entry, dashboard tiles, breadcrumb).
        {
            location: "/template-application-ui-harmonia-java/ui/translations-report.json.template",
            action: "translate",
        },
        // --- Framework-neutral Java backend (same as the AngularJS report-file template) ---
        {
            location: "/template-application-dao-java/data/reportFileEntity.java.template",
            action: "generate",
            rename: "gen/{{javaGenFolderName}}/data/{{javaPerspectiveName}}/{{name}}Repository.java",
            engine: "velocity",
            collection: "reportModels"
        }, {
            location: "/template-application-rest-java/api/reportFileEntity.java.template",
            action: "generate",
            rename: "gen/{{javaGenFolderName}}/api/{{javaPerspectiveName}}/{{name}}Controller.java",
            engine: "velocity",
            collection: "reportModels"
        }, {
            location: "/template-application-rest-java/roles/default-roles.roles.template",
            action: "generate",
            rename: "gen/{{javaGenFolderName}}/roles/default-roles.roles",
            engine: "velocity",
            collection: "reportModels"
        }, {
            location: "/template-application-rest-java/project.json.mjs",
            action: "generate",
            rename: "project.json",
            engine: "javascript"
        },
        // --- Harmonia UI: a self-contained report page ---
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/report-file/index.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/reports/{{name}}/index.html",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/report-file/report.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/reports/{{name}}/report.js",
            collection: "generateReportModels"
        }
    ];
};
