/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */

/*
 * Setting view (SETTING entities) — nomenclature / configuration entities (e.g. Country, City).
 *
 * Settings get the same CRUD treatment as a MANAGE entity, so this reuses the `manage` view
 * templates verbatim against the `uiSettingModels` collection (entities with type === "SETTING").
 * Their perspective resolves to "Settings", so the generated controller path the page components
 * derive — <restBase>/settings/<Entity>Controller — matches the backend the REST template emits,
 * and the shell groups them under a "Settings" sidebar section (see ui/shell/index.html.template).
 */
export function getSources(parameters) {
    return [
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/manage/list-page.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/js/components/pages/{{perspectiveName}}/{{name}}ManageListPage.js",
            collection: "uiSettingModels"
        },
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/manage/list-view.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/views/{{perspectiveName}}/{{name}}-manage-list.html",
            collection: "uiSettingModels"
        },
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/manage/form-page.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/js/components/pages/{{perspectiveName}}/{{name}}FormPage.js",
            collection: "uiSettingModels"
        },
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/manage/form-view.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/views/{{perspectiveName}}/{{name}}-form.html",
            collection: "uiSettingModels"
        }
    ];
};
