/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */

/*
 * Shell sources — the reusable Alpine.js + Harmonia runtime dashboard.
 *
 * These files are the directly-adopted dashboard from codbex-athena-app (see
 * HARMONIA_RUNTIME_PLAN.md, "Reference implementation"). They are app-wide and
 * model-independent, so they are emitted ONCE per generated app with action "copy"
 * (verbatim content; only the destination path is Mustache-processed).
 *
 * The single exception is index.html, which is the aggregate SPA entry: it must
 * enumerate every entity's <template x-route> and sidebar nav entry, so it is
 * generated ONCE over the whole model (no `collection` => generateUtils exposes
 * `parameters.models = model.entities` to Velocity).
 *
 * TODO (Phase 1): vendor Alpine 3.15 + @codbex/harmonia + Pinecone 7.5 + Lucide as
 * webjars and reference them from index.html instead of unpkg CDN (CSP/offline).
 */
export function getSources() {
    return [
        // Aggregate SPA entry — generated once over the full model.
        {
            location: "/template-application-ui-harmonia-java/ui/shell/index.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/index.html"
        },
        // The one project-specific shell file: the runtime config (REST base, SPA
        // basePath, project name). Generated so the verbatim assets below can stay
        // model-independent and read their wiring from `window.App.config`.
        {
            location: "/template-application-ui-harmonia-java/ui/shell/js/config.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/js/config.js"
        },
        // Settings + Reports landing pages — generated once over the full model (no collection) so
        // each lists its entities; reached via the single Settings / Reports sidebar entries.
        {
            location: "/template-application-ui-harmonia-java/ui/shell/settings.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/views/_settings.html"
        },
        {
            location: "/template-application-ui-harmonia-java/ui/shell/reports.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/views/_reports.html"
        },
        // Static, model-independent shell assets — copied verbatim.
        {
            location: "/template-application-ui-harmonia-java/ui/shell/js/app.js.template",
            action: "copy",
            rename: "gen/{{genFolderName}}/js/app.js"
        },
        {
            location: "/template-application-ui-harmonia-java/ui/shell/js/services/api.js.template",
            action: "copy",
            rename: "gen/{{genFolderName}}/js/services/api.js"
        },
        {
            location: "/template-application-ui-harmonia-java/ui/shell/js/services/apiError.js.template",
            action: "copy",
            rename: "gen/{{genFolderName}}/js/services/apiError.js"
        },
        {
            location: "/template-application-ui-harmonia-java/ui/shell/js/services/formValidation.js.template",
            action: "copy",
            rename: "gen/{{genFolderName}}/js/services/formValidation.js"
        },
        {
            location: "/template-application-ui-harmonia-java/ui/shell/js/components/layout/appShell.js.template",
            action: "copy",
            rename: "gen/{{genFolderName}}/js/components/layout/appShell.js"
        },
        {
            location: "/template-application-ui-harmonia-java/ui/shell/js/components/pages/basePage.js.template",
            action: "copy",
            rename: "gen/{{genFolderName}}/js/components/pages/basePage.js"
        },
        {
            location: "/template-application-ui-harmonia-java/ui/shell/js/components/detailPanel.js.template",
            action: "copy",
            rename: "gen/{{genFolderName}}/js/components/detailPanel.js"
        },
        {
            location: "/template-application-ui-harmonia-java/ui/shell/js/stores/processTasks.js.template",
            action: "copy",
            rename: "gen/{{genFolderName}}/js/stores/processTasks.js"
        },
        {
            location: "/template-application-ui-harmonia-java/ui/shell/js/stores/reports.js.template",
            action: "copy",
            rename: "gen/{{genFolderName}}/js/stores/reports.js"
        },
        {
            location: "/template-application-ui-harmonia-java/ui/shell/js/components/pages/baseFormPage.js.template",
            action: "copy",
            rename: "gen/{{genFolderName}}/js/components/pages/baseFormPage.js"
        },
        {
            location: "/template-application-ui-harmonia-java/ui/shell/css/app.css.template",
            action: "copy",
            rename: "gen/{{genFolderName}}/css/app.css"
        },
        {
            location: "/template-application-ui-harmonia-java/ui/shell/notfound.html.template",
            action: "copy",
            rename: "gen/{{genFolderName}}/views/_notfound.html"
        },
        // Built-in shell sections (transferred from the dashboard): Process Inbox + Documents.
        {
            location: "/template-application-ui-harmonia-java/ui/shell/js/components/pages/inboxPage.js.template",
            action: "copy",
            rename: "gen/{{genFolderName}}/js/components/pages/inboxPage.js"
        },
        {
            location: "/template-application-ui-harmonia-java/ui/shell/inbox.html.template",
            action: "copy",
            rename: "gen/{{genFolderName}}/views/_inbox.html"
        },
        {
            location: "/template-application-ui-harmonia-java/ui/shell/js/components/pages/documentsPage.js.template",
            action: "copy",
            rename: "gen/{{genFolderName}}/js/components/pages/documentsPage.js"
        },
        {
            location: "/template-application-ui-harmonia-java/ui/shell/documents.html.template",
            action: "copy",
            rename: "gen/{{genFolderName}}/views/_documents.html"
        }
    ];
};
