/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */

/*
 * Shell sources.
 *
 * The model-independent Harmonia runtime (app.js, services, stores, base/page components, appShell,
 * css, and the Inbox/Documents/Reports/notfound views) is NO LONGER copied per project: it is served
 * once from the shared location /services/web/application-core/shell (see
 * components/resources/application-core/.../application-core/shell), which the generated index.html
 * references directly. The same shared runtime backs the Harmonia application shell
 * (components/resources/resources-application), so there is a single source of truth.
 *
 * Only the project-specific files are still generated here:
 *   - index.html        : the aggregate SPA entry (enumerates entity routes + sidebar nav)
 *   - js/config.js      : the runtime config (REST base, SPA basePath, project name)
 *   - views/_settings.html : lists THIS project's setting entities
 *   - js/.../dashboardPage.js + views/_dashboard.html : the home KPI tiles, baked from the model
 */
export function getSources() {
    return [
        // Aggregate SPA entry — generated once over the full model.
        {
            location: "/template-application-ui-harmonia-java/ui/shell/index.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/index.html"
        },
        // The one project-specific runtime config (REST base, SPA basePath, project name). The shared
        // runtime reads its wiring from window.App.config.
        {
            location: "/template-application-ui-harmonia-java/ui/shell/js/config.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/js/config.js"
        },
        // Settings landing — generated once over the full model so it lists this project's settings.
        {
            location: "/template-application-ui-harmonia-java/ui/shell/settings.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/views/_settings.html"
        },
        // Home dashboard: the page component bakes one KPI tile per entity from the model (velocity);
        // the view is generic (iterates the component's data).
        {
            location: "/template-application-ui-harmonia-java/ui/shell/js/components/pages/dashboardPage.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/js/components/pages/dashboardPage.js"
        },
        {
            location: "/template-application-ui-harmonia-java/ui/shell/dashboard.html.template",
            action: "copy",
            rename: "gen/{{genFolderName}}/views/_dashboard.html"
        }
    ];
};
