/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */

/*
 * Slots view type — Harmonia SPA variant.
 *
 * A PRIMARY entity declared with `view: slots` is emitted by EdmIntentGenerator with layoutType
 * MANAGE_SLOTS plus the slot* metadata (slotStartProperty / slotOpen / slotClose / slotStep /
 * slotDisabledDays). It renders as a Harmonia x-h-slot-picker (a 3-day grid of selectable time slots):
 * free slots are bookable, already-booked slots (from the entity's own records) are shown taken, and
 * picking a slot opens the shared create form prefilled with the chosen datetime (?<Start>=…).
 *
 *   /<Entity>            -> the slot-picker page
 *   /<Entity>/create     -> the shared form (create; opened on slot-click)
 *   /<Entity>/{id}/edit  -> the shared form (edit)
 *
 * Collection: uiSlotsModels = layoutType === "MANAGE_SLOTS" && type === "PRIMARY".
 */
export function getSources(parameters) {
    const collection = "uiSlotsModels";
    return [
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/slots/slots-page.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/js/components/pages/{{perspectiveName}}/{{name}}SlotsPage.js",
            collection
        },
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/slots/slots-view.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/views/{{perspectiveName}}/{{name}}-slots.html",
            collection
        },
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/manage/form-page.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/js/components/pages/{{perspectiveName}}/{{name}}FormPage.js",
            collection
        },
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/manage/form-view.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/views/{{perspectiveName}}/{{name}}-form.html",
            collection
        }
    ];
};
