/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */

// SPA shell — static, app-wide assets copied verbatim (the reusable Harmonia dashboard,
// adapted from codbex-athena-app: appShell, fetch entity client, error/i18n catalog,
// page-base mixins, form validation). See ui/shell/*.
import * as shellTemplate from "template-application-ui-harmonia-java/template/ui/shell";

// Per view-type generators (Velocity over the model's UI collections).
import * as listTemplate from "template-application-ui-harmonia-java/template/ui/list";
import * as manageTemplate from "template-application-ui-harmonia-java/template/ui/manage";
import * as settingTemplate from "template-application-ui-harmonia-java/template/ui/setting";
import * as navigation from "template-application-ui-harmonia-java/template/ui/navigation";

// TODO (Phase 2 — full parity): wire the remaining view types, mirroring the Angular
// module's collections. Each is a thin source-collector that emits Harmonia view
// fragments + Alpine.data page components + <template x-route> declarations.
// import * as masterDetailsListTemplate from "template-application-ui-harmonia-java/template/ui/masterDetailsList";
// import * as masterDetailsManageTemplate from "template-application-ui-harmonia-java/template/ui/masterDetailsManage";
// import * as settingTemplate from "template-application-ui-harmonia-java/template/ui/setting";
// import * as reportTemplate from "template-application-ui-harmonia-java/template/ui/report";
// import * as reportChartTemplate from "template-application-ui-harmonia-java/template/ui/reportChart";
// import * as reportTableTemplate from "template-application-ui-harmonia-java/template/ui/reportTable";

export function getSources(parameters) {
    return [
        {
            location: "/template-application-ui-harmonia-java/ui/translations.json.template",
            action: "translate",
        },
        ...shellTemplate.getSources(parameters),
        ...listTemplate.getSources(parameters),
        ...manageTemplate.getSources(parameters),
        ...settingTemplate.getSources(parameters),
        ...navigation.getSources(parameters),
        // TODO (Phase 2): ...masterDetailsListTemplate.getSources(parameters),
        // TODO (Phase 2): ...masterDetailsManageTemplate.getSources(parameters),
        // TODO (Phase 2): ...settingTemplate.getSources(parameters),
        // TODO (Phase 3): ...reportTemplate.getSources(parameters),
        // TODO (Phase 3): ...reportChartTemplate.getSources(parameters),
        // TODO (Phase 3): ...reportTableTemplate.getSources(parameters),
    ];
};
