/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */

// SPA shell — static, app-wide assets copied verbatim (the reusable Harmonia dashboard,
// adapted from codbex-athena-app: appShell, fetch entity client, error/i18n catalog,
// page-base mixins, form validation). See ui/shell/*.
import * as shellTemplate from "template-application-ui-harmonia-java/template/ui/shell";

// Per view-type generators (Velocity over the model's UI collections).
import * as listTemplate from "template-application-ui-harmonia-java/template/ui/list";
import * as manageTemplate from "template-application-ui-harmonia-java/template/ui/manage";
import * as settingTemplate from "template-application-ui-harmonia-java/template/ui/setting";
import * as masterDetailTemplate from "template-application-ui-harmonia-java/template/ui/masterDetail";
import * as documentTemplate from "template-application-ui-harmonia-java/template/ui/document";
import * as calendarTemplate from "template-application-ui-harmonia-java/template/ui/calendar";
import * as reportTemplate from "template-application-ui-harmonia-java/template/ui/report";
import * as navigation from "template-application-ui-harmonia-java/template/ui/navigation";

// The Harmonia form runtime (.form artifacts incl. BPM task forms) is its own module:
// template-form-builder-harmonia (the intent recipe's `form` template).

export function getSources(parameters) {
    return [
        {
            location: "/template-application-ui-harmonia-java/ui/translations.json.template",
            action: "translate",
        },
        ...shellTemplate.getSources(parameters),
        ...listTemplate.getSources(parameters),
        ...manageTemplate.getSources(parameters),
        ...settingTemplate.getSources(parameters),
        ...masterDetailTemplate.getSources(parameters),
        ...documentTemplate.getSources(parameters),
        ...calendarTemplate.getSources(parameters),
        ...reportTemplate.getSources(parameters),
        ...navigation.getSources(parameters),
    ];
};
