/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */

// SPA shell — static, app-wide assets copied verbatim (the reusable Harmonia dashboard,
// adapted from codbex-athena-app: appShell, fetch entity client, error/i18n catalog,
// page-base mixins, form validation). See ui/shell/*.
import * as shellTemplate from "template-application-ui-harmonia-java/template/ui/shell";

// Per view-type generators (Velocity over the model's UI collections).
import * as listTemplate from "template-application-ui-harmonia-java/template/ui/list";
import * as manageTemplate from "template-application-ui-harmonia-java/template/ui/manage";
import * as settingTemplate from "template-application-ui-harmonia-java/template/ui/setting";
import * as masterDetailTemplate from "template-application-ui-harmonia-java/template/ui/masterDetail";
import * as navigation from "template-application-ui-harmonia-java/template/ui/navigation";

// TODO (Phase 3 — reports & forms): report / report-chart / report-table view types, plus the
// Harmonia form runtime (.form artifacts incl. BPM task forms). Each is a thin source-collector
// emitting Harmonia view fragments + Alpine.data page components + <template x-route> declarations.

export function getSources(parameters) {
    return [
        {
            location: "/template-application-ui-harmonia-java/ui/translations.json.template",
            action: "translate",
        },
        ...shellTemplate.getSources(parameters),
        ...listTemplate.getSources(parameters),
        ...manageTemplate.getSources(parameters),
        ...settingTemplate.getSources(parameters),
        ...masterDetailTemplate.getSources(parameters),
        ...navigation.getSources(parameters),
        // TODO (Phase 3 — reports): report / report-chart / report-table view types.
    ];
};
