/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */

export function getTemplate(parameters) {
    return {
        name: "Generator from Mapping Model - Java",
        description: "Mapping Model Generator Template - client Java",
        extension: "mapping",
        sources: [
            {
                location: "/template-mapping-java/mapper.java.template",
                action: "generate",
                rename: "gen/{{javaGenFolderName}}/mappings/{{mapperClassName}}.java",
                engine: "velocity",
            }
        ],
        parameters: []
    };
}
