/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
import * as generateUtils from "service-generate/template/generateUtils";
import { sanitizeJavaIdentifier } from "service-generate/template/parameterUtils";

// The mapping model reaches a template as the raw file text (generate.mjs only parses .model files),
// so the JSON is parsed here rather than assumed to be an object.
function parseModel(model) {
    return typeof model === "string" ? JSON.parse(model) : model;
}

function toClassName(name) {
    const words = String(name || "").split(/[^A-Za-z0-9]+/).filter(word => word.length > 0);
    if (words.length === 0) {
        return "Mapper";
    }
    const className = words.map(word => word.charAt(0).toUpperCase() + word.substring(1)).join("");
    return /^[0-9]/.test(className) ? `_${className}` : className;
}

function javaString(value) {
    return `"${String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\r?\n/g, "\\n")}"`;
}

// A column's `scale` decides how a formula result is rounded. The mapping editor only writes it for
// decimal columns, so everything else falls back to two decimal places.
function scaleOf(column) {
    const scale = Number(column.scale);
    return Number.isInteger(scale) && scale >= 0 ? scale : 2;
}

// `criteria` is authored as a comparison suffix appended to the mapped value ("> 100", "== null").
// The TypeScript generator eval'd `value + criteria` at runtime; here it is parsed at generation
// time into a typed Java comparison, so an unparseable criteria fails the generation loudly instead
// of emitting code that misbehaves later.
function criteriaExpression(column, valueExpression) {
    const match = /^\s*(===|!==|==|!=|>=|<=|>|<)\s*(.+?)\s*$/.exec(column.criteria);
    if (!match) {
        throw new Error(`Column '${column.name}': criteria '${column.criteria}' is not a comparison. `
            + `Expected an operator (==, !=, >, <, >=, <=) followed by a number, a quoted string or null.`);
    }
    const operator = match[1].replace("===", "==").replace("!==", "!=");
    const operand = match[2];

    if (operand === "null") {
        return `${valueExpression} ${operator === "==" ? "==" : "!="} null`;
    }
    const quoted = /^'(.*)'$|^"(.*)"$/.exec(operand);
    if (quoted) {
        const literal = javaString(quoted[1] !== undefined ? quoted[1] : quoted[2]);
        const equals = `java.util.Objects.equals(${valueExpression}, ${literal})`;
        return operator === "==" ? equals : `!${equals}`;
    }
    if (!/^[+-]?[0-9]+(\.[0-9]+)?$/.test(operand)) {
        throw new Error(`Column '${column.name}': criteria operand '${operand}' is not a number, `
            + `a quoted string or null.`);
    }
    return `number(${valueExpression}) ${operator} ${operand}d`;
}

// Precedence matches the TypeScript generator, whose sequential assignments left the last-declared
// source winning: module, then formula, then constant, then direct.
function valueExpression(column) {
    if (column.module) {
        return {
            expression: `org.eclipse.dirigible.sdk.component.Beans.get(${column.module}.class)`
                + `.map(source, target, ${javaString(column.name)})`,
            usesBeans: true
        };
    }
    if (column.formula) {
        return {
            expression: `org.eclipse.dirigible.sdk.utils.Calc.eval(${javaString(column.formula)}, source, ${scaleOf(column)})`,
            usesCalc: true
        };
    }
    if (column.constant) {
        return { expression: javaString(column.constant) };
    }
    if (column.direct) {
        return { expression: `source.get(${javaString(column.direct)})` };
    }
    return { expression: "null" };
}

function buildColumns(structures) {
    const targets = structures.filter(structure => structure.type === "TARGET");
    if (targets.length === 0) {
        throw new Error("The mapping model declares no TARGET structure - nothing to map to.");
    }
    // The TypeScript generator kept the last TARGET it saw; preserved so an existing model generates
    // the same mapping in both languages.
    const target = targets[targets.length - 1];
    const columns = target.columns || [];

    let usesCalc = false;
    let usesNumber = false;
    let usesBeans = false;

    const mapped = columns.map(column => {
        const value = valueExpression(column);
        usesCalc = usesCalc || Boolean(value.usesCalc);
        usesBeans = usesBeans || Boolean(value.usesBeans);
        const entry = {
            name: column.name,
            nameLiteral: javaString(column.name),
            expression: value.expression
        };
        if (column.criteria) {
            entry.criteria = criteriaExpression(column, `target.get(${javaString(column.name)})`);
            usesNumber = usesNumber || entry.criteria.startsWith("number(");
        }
        return entry;
    });

    return { targetName: target.name, columns: mapped, usesCalc, usesNumber, usesBeans };
}

export function generate(model, parameters) {
    const parsed = parseModel(model);
    const structures = (parsed && parsed.mapping && parsed.mapping.structures) || [];
    const built = buildColumns(structures);

    parameters.javaGenFolderName = sanitizeJavaIdentifier(parameters.genFolderName);
    parameters.mapperClassName = toClassName(parameters.fileName);

    const templateModel = {
        mappingTarget: built.targetName,
        mappingColumns: built.columns,
        usesNumber: built.usesNumber
    };
    const templateSources = getTemplate(parameters).sources;
    return generateUtils.generateGeneric(templateModel, parameters, templateSources);
}

export function getTemplate(parameters) {
    return {
        name: "Generator from Mapping Model - Java",
        description: "Mapping Model Generator Template - client Java",
        extension: "mapping",
        sources: [
            {
                location: "/template-mapping-java/mapper.java.template",
                action: "generate",
                rename: "gen/{{javaGenFolderName}}/mappings/{{mapperClassName}}.java",
                engine: "velocity",
            }
        ],
        parameters: []
    };
}
