/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */

export function getSources(parameters) {
    const sources = [];

    sources.push(...getTableReportBackendSources());
    sources.push(...getTableReportUISource());

    return sources;
};

function getTableReportBackendSources() {
    return [
        {
            location: "/template-application-dao-java/data/reportFileEntity.java.template",
            action: "generate",
            rename: "gen/{{javaGenFolderName}}/data/{{javaPerspectiveName}}/{{name}}Repository.java",
            engine: "velocity",
            collection: "reportModels"
        }, {
            location: "/template-application-rest-java/api/reportFileEntity.java.template",
            action: "generate",
            rename: "gen/{{javaGenFolderName}}/api/{{javaPerspectiveName}}/{{name}}Controller.java",
            engine: "velocity",
            collection: "reportModels"
        }, {
            location: "/template-application-rest-java/roles/default-roles.roles.template",
            action: "generate",
            rename: "gen/{{javaGenFolderName}}/roles/default-roles.roles",
            engine: "velocity",
            collection: "reportModels"
        }, {
            location: "/template-application-rest-java/project.json.mjs",
            action: "generate",
            rename: "project.json",
            engine: "javascript"
        }
    ];
}

function getTableReportUISource() {
    return [
        {
            location: "/template-application-ui-angular-java/ui/translations-report.json.template",
            action: "translate",
        },
        {
            location: "/template-application-ui-angular-java/ui/perspective/report-file/dialog-window/controller.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-window/controller.js",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular-java/ui/perspective/report-file/dialog-window/index.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-window/index.html",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular-java/ui/perspective/report-file/dialog-window/view.extension.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-window/view.extension",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular-java/ui/perspective/report-file/dialog-window/view.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-window/view.js",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular-java/ui/perspective/report-file/dialog-filter/controller.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-filter/controller.js",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular-java/ui/perspective/report-file/dialog-filter/index.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-filter/index.html",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular-java/ui/perspective/report-file/dialog-filter/view.extension.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-filter/view.extension",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular-java/ui/perspective/report-file/dialog-filter/view.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-filter/view.js",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular-java/ui/perspective/report-file/controller.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/controller.js",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular-java/ui/perspective/report-file/index.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/index.html",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular-java/ui/perspective/report-file/view.extension.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/view.extension",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular-java/ui/perspective/report-file/view.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/view.js",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular-java/ui/perspective/report-file/dialog-print/controller.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-print/controller.js",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular-java/ui/perspective/report-file/dialog-print/index.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-print/index.html",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular-java/ui/perspective/report-file/dialog-print/print.extension.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-print/print.extension",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular-java/ui/perspective/report-file/dialog-print/print.js.template",
            action: "generate",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-print/print.js",
            collection: "generateReportModels"
        }];
}
