/*
 * Copyright (c) 2010-2026 Eclipse Dirigible contributors
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: Eclipse Dirigible contributors
 * SPDX-License-Identifier: EPL-2.0
 */
/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * currentUser store — the logged-in platform user (name + initials) and log-out, for the shell's
 * top-right user menu. The name comes from the platform's user-name service; log-out redirects to
 * the platform /logout endpoint (the same one the IDE shell uses).
 */
document.addEventListener('alpine:init', () => {
  Alpine.store('currentUser', {
    name: '',

    get initials() {
      const n = (this.name || '').trim();
      if (!n) return '?';
      const parts = n.split(/[\s._@-]+/).filter(Boolean);
      const first = (parts[0] || '')[0] || '';
      const last = parts.length > 1 ? (parts[parts.length - 1] || '')[0] || '' : '';
      return (first + last).toUpperCase() || n[0].toUpperCase();
    },

    init() { this.load(); },

    async load() {
      try {
        const r = await fetch('/services/js/platform-core/services/user-name.js', {
          headers: { 'Accept': 'text/plain' }, credentials: 'same-origin',
        });
        if (r.ok) this.name = (await r.text()).trim();
      } catch (e) {
        console.error('currentUser: could not load the user name', e);
      }
    },

    logout() { window.location.replace('/logout'); },
  });
}, { once: true });
