/*
 * Copyright (c) 2010-2026 Eclipse Dirigible contributors
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: Eclipse Dirigible contributors
 * SPDX-License-Identifier: EPL-2.0
 */
/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * notifications store — the shell's in-app notification list behind the top-right bell. App code /
 * glue pushes entries via Alpine.store('notifications').add({ title, description, variant }); the
 * bell shows the unread count and the dropdown lists them. (Transient toasts are a separate concern,
 * via Harmonia's $notifications overlay declared in index.html.)
 *
 * A first source is wired in: the user's actionable BPM tasks (from the processTasks store) are
 * surfaced as notifications via syncTasks() — a new task shows up here, a completed one drops off.
 * TODO (follow-up): a persistent, server-side per-user notification inbox.
 */
document.addEventListener('alpine:init', () => {
  Alpine.store('notifications', {
    items: [],   // [{ id, title, description, variant, unread }]
    _seq: 0,

    get unreadCount() { return this.items.filter(n => n.unread).length; },

    add(n) {
      n = n || {};
      this.items.unshift({
        id: n.id || ('n' + (++this._seq)),
        title: n.title || '',
        description: n.description || '',
        variant: n.variant || 'information',
        unread: true,
      });
    },

    markAllRead() { this.items.forEach(n => { n.unread = false; }); },
    remove(id) { this.items = this.items.filter(n => n.id !== id); },
    clear() { this.items = []; },

    // Reconcile task-derived notifications against the current BPM tasks (called by processTasks):
    // keep app-pushed items and still-pending task items (preserving their read state), drop tasks
    // that are gone, and add new tasks at the top.
    syncTasks(tasks) {
      tasks = tasks || [];
      const taskIds = new Set(tasks.map(t => 'task:' + t.id));
      const kept = this.items.filter(n => n.source !== 'task' || taskIds.has(n.id));
      const existing = new Set(kept.map(n => n.id));
      const added = [];
      tasks.forEach(t => {
        const id = 'task:' + t.id;
        if (!existing.has(id)) {
          added.push({
            id,
            source: 'task',
            task: t,
            title: 'New task: ' + (t.name || 'Task'),
            description: t.processDefinitionName || '',
            variant: 'information',
            unread: true,
          });
        }
      });
      this.items = added.concat(kept);
    },
  });
}, { once: true });
