/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
export const getTemplate = () => ({
  name: "HTTP Client (API)",
  description: "Client Java Service With HTTP Client Support",
  sources: [
    {
      location: "/template-http-client/service.java.template",
      action: "generate",
      rename: "{{javaPackageName}}/{{javaClassName}}.java",
    },
  ],
  parameters: [],
  order: 20,
});
