/*
 * Copyright (c) 2010-2026 Eclipse Dirigible contributors
 *
 * All rights reserved. This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: Eclipse Dirigible contributors SPDX-License-Identifier: EPL-2.0
 */
package org.eclipse.dirigible.components.intent.domain;

import org.eclipse.dirigible.components.base.artefact.Artefact;

import com.google.gson.annotations.Expose;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;

/**
 * Persisted projection of an {@code .intent} YAML file. The file itself is the only artefact a
 * developer authors; every downstream model (entity, schema, BPMN, form, report, controller) is
 * regenerated by {@code IntentSynchronizer} into the {@code gen/} folder of the same project.
 */
@Entity
@Table(name = "DIRIGIBLE_INTENTS")
public class Intent extends Artefact {

    /** Artefact type discriminator stored in {@code ARTEFACT_TYPE}. */
    public static final String ARTEFACT_TYPE = "intent";

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "INTENT_ID", nullable = false)
    private Long id;

    /**
     * Raw YAML payload of the {@code .intent} file, post-placeholder-expansion. Persisted so the
     * regeneration step can run from the DB row without re-reading the repository. The {@code TEXT}
     * column definition follows the platform convention for content-bearing artefacts (Bpmn, Camel,
     * OpenAPI) and is proven portable across the H2 / PostgreSQL / MSSQL CI matrix - {@code CLOB} is
     * not.
     */
    @Column(name = "INTENT_CONTENT", columnDefinition = "TEXT", nullable = false)
    @Expose
    private String content;

    /**
     * Transient typed view of {@link #content}, hydrated by {@code IntentParser} for the regeneration
     * pass. Not persisted.
     */
    @Transient
    private transient Object model;

    public Intent() {}

    public Intent(String location, String name, String description, String content) {
        super(location, name, ARTEFACT_TYPE, description, null);
        this.content = content;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Object getModel() {
        return model;
    }

    public void setModel(Object model) {
        this.model = model;
    }

    @Override
    public String toString() {
        return "Intent{" + "id=" + id + ", location='" + location + '\'' + ", name='" + name + '\'' + ", type='" + type + '\'' + ", key='"
                + key + '\'' + ", lifecycle=" + lifecycle + '}';
    }
}
