/*
 * Copyright (c) 2010-2026 Eclipse Dirigible contributors
 *
 * All rights reserved. This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: Eclipse Dirigible contributors SPDX-License-Identifier: EPL-2.0
 */
package org.eclipse.dirigible.components.ide.template.service.model;

import org.eclipse.dirigible.components.ide.template.domain.GenerationTemplateMetadata;
import org.eclipse.dirigible.components.ide.template.domain.GenerationTemplateMetadataSource;
import org.eclipse.dirigible.components.ide.template.service.GenerationService;
import org.eclipse.dirigible.components.ide.workspace.domain.File;
import org.eclipse.dirigible.components.ide.workspace.domain.Folder;
import org.eclipse.dirigible.components.ide.workspace.domain.Project;
import org.eclipse.dirigible.components.ide.workspace.domain.Workspace;
import org.eclipse.dirigible.components.ide.workspace.service.PublisherService;
import org.eclipse.dirigible.components.ide.workspace.service.WorkspaceService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import static org.eclipse.dirigible.components.ide.template.service.model.ModelValues.asMap;
import static org.eclipse.dirigible.components.ide.template.service.model.ModelValues.asMaps;
import static org.eclipse.dirigible.components.ide.template.service.model.ModelValues.str;

/**
 * Generates a project's artefacts from one of its model files.
 *
 * <p>
 * The pipeline is: read the model, fold in the entity extensions other projects contribute to it,
 * render the template's sources, clear the generation folders this run writes into, write the
 * files, record what it was generated with, and publish. It is the Java counterpart of the
 * generation endpoint the browser has been calling, and it renders in-process rather than one HTTP
 * round trip per source file.
 */
@Component
public class ModelGenerationService {

    /** The Constant logger. */
    private static final Logger logger = LoggerFactory.getLogger(ModelGenerationService.class);

    /** The folder every generation writes into. */
    private static final String GENERATION_FOLDER = "gen";

    /** The extension of the descriptor recording what a model was generated with. */
    private static final String DESCRIPTOR_EXTENSION = ".gen";

    /** The workspace service. */
    private final WorkspaceService workspaceService;

    /** The publisher service. */
    private final PublisherService publisherService;

    /** The generator. */
    private final ModelGenerator modelGenerator;

    /** The per-generation consumed-attributes manifest. */
    private final ConsumedAttributesAudit consumedAttributesAudit;

    /**
     * Instantiates a new model generation service.
     *
     * @param workspaceService the workspace service
     * @param publisherService the publisher service
     * @param modelGenerator the model generator
     * @param consumedAttributesAudit the consumed-attributes manifest
     */
    ModelGenerationService(WorkspaceService workspaceService, PublisherService publisherService, ModelGenerator modelGenerator,
            ConsumedAttributesAudit consumedAttributesAudit) {
        this.workspaceService = workspaceService;
        this.publisherService = publisherService;
        this.modelGenerator = modelGenerator;
        this.consumedAttributesAudit = consumedAttributesAudit;
    }

    /**
     * Tests whether a template can be generated by this pipeline.
     *
     * @param templateId the template's module path
     * @return true when it is supported
     */
    public boolean supports(String templateId) {
        return ModelTemplateAdapters.supports(templateId);
    }

    /**
     * Renders everything a generation would write, without writing any of it - the rendered files plus
     * the descriptor recording what the model was generated with.
     *
     * @param workspace the workspace name
     * @param project the project name
     * @param path the project-relative path of the model file
     * @param templateId the template's module path
     * @param parameters the generation parameters from the request, mutated with the derived ones
     * @return the files a generation would write
     * @throws IOException when the model or a template is missing, or rendering fails
     */
    public List<GeneratedFile> render(String workspace, String project, String path, String templateId, Map<String, Object> parameters)
            throws IOException {
        Workspace workspaceObject = requireWorkspace(workspace);
        Project projectObject = requireProject(workspaceObject, workspace, project);
        String modelText = augmentWithExtensions(readModel(projectObject, workspace, project, path), workspaceObject, project);

        addStandardParameters(parameters, workspace, project, path, templateId);
        // The descriptor is read before the parameters are derived, which is the order the template
        // modules themselves use - a composite descriptor assembles its source list from the request's
        // parameters, never from the derived ones.
        List<GenerationTemplateMetadataSource> sources = readSources(templateId, parameters);
        ModelTemplateAdapters.PreparedModel prepared = ModelTemplateAdapters.prepare(templateId, modelText, parameters);
        List<GeneratedFile> rendered = prepared.entityShaped() ? modelGenerator.generateFiles(prepared.model(), parameters, sources)
                : modelGenerator.generateGeneric(prepared.model(), parameters, sources);

        List<GeneratedFile> files = new ArrayList<>(rendered.size() + 1);
        files.addAll(rendered);
        files.add(new GeneratedFile(null, str(parameters, "fileName") + DESCRIPTOR_EXTENSION, JavaScriptJson.pretty(parameters)));
        return files;
    }

    /**
     * The per-generation consumed-attributes manifest for one model file: the attributes it sets that
     * neither the template nor the generation stages read (dirigible #6543).
     *
     * <p>
     * Run alongside a generation rather than inside it: an unread attribute costs the generated code a
     * feature, not the generation its result, so it is reported and never thrown. The model text and
     * the template sources are read exactly as {@link #render} reads them - the extensions folded in,
     * the descriptor consulted with the request's parameters - so what is audited is what was generated
     * from.
     *
     * @param workspace the workspace name
     * @param project the project name
     * @param path the project-relative path of the model file
     * @param templateId the template's module path
     * @param parameters the generation parameters from the request; not mutated
     * @return one warning per unclaimed attribute, empty when everything the model sets is claimed
     * @throws IOException when the model is missing
     */
    public List<String> auditConsumedAttributes(String workspace, String project, String path, String templateId,
            Map<String, Object> parameters) throws IOException {
        Workspace workspaceObject = requireWorkspace(workspace);
        Project projectObject = requireProject(workspaceObject, workspace, project);
        String modelText = augmentWithExtensions(readModel(projectObject, workspace, project, path), workspaceObject, project);
        // A copy, and the standard parameters added before the descriptor is read: the order render()
        // uses, so a composite descriptor assembles the same source list here as it did there.
        Map<String, Object> descriptorParameters = parameters == null ? new LinkedHashMap<>() : new LinkedHashMap<>(parameters);
        addStandardParameters(descriptorParameters, workspace, project, path, templateId);
        return consumedAttributesAudit.audit(path, modelText, templateId, descriptorParameters);
    }

    /**
     * Renders a template against a model file and writes the result into the project, then publishes
     * it.
     *
     * @param workspace the workspace name
     * @param project the project name
     * @param path the project-relative path of the model file
     * @param templateId the template's module path
     * @param parameters the generation parameters from the request
     * @return the written files
     * @throws IOException when the model or a template is missing, or rendering fails
     */
    public List<File> generate(String workspace, String project, String path, String templateId, Map<String, Object> parameters)
            throws IOException {
        Map<String, Object> effectiveParameters = parameters == null ? new LinkedHashMap<>() : parameters;
        List<GeneratedFile> generated = render(workspace, project, path, templateId, effectiveParameters);

        Workspace workspaceObject = requireWorkspace(workspace);
        Project projectObject = requireProject(workspaceObject, workspace, project);
        clearGenerationFolders(projectObject, project, generated);

        List<File> written = new ArrayList<>(generated.size());
        for (GeneratedFile file : generated) {
            written.add(write(projectObject, file.path(), file.content()));
        }
        publisherService.publish(workspace, project, "");
        return written;
    }

    /**
     * Adds the parameters every template can rely on, derived from where the model file lives.
     *
     * @param parameters the generation parameters
     * @param workspace the workspace name
     * @param project the project name
     * @param path the project-relative path of the model file
     * @param templateId the template's module path
     */
    private static void addStandardParameters(Map<String, Object> parameters, String workspace, String project, String path,
            String templateId) {
        parameters.put("projectName", project);
        parameters.put("workspaceName", workspace);
        parameters.put("filePath", path);
        parameters.put("templateId", templateId);
        int dot = path.indexOf('.');
        String fileName = dot > 0 ? path.substring(0, dot) : path;
        parameters.put("fileName", fileName);
        parameters.put("genFolderName", fileName);
    }

    /**
     * Reads a template's source list. The descriptors are still authored as template modules, so this
     * asks the existing generation service for the parsed descriptor.
     *
     * @param templateId the template's module path
     * @param parameters the generation parameters the descriptor may branch on
     * @return the template sources
     * @throws IOException when the descriptor declares no sources
     */
    private static List<GenerationTemplateMetadataSource> readSources(String templateId, Map<String, Object> parameters)
            throws IOException {
        GenerationTemplateMetadata metadata = GenerationService.getTemplateMetadata(templateId, parameters);
        List<GenerationTemplateMetadataSource> sources = metadata.getSources();
        if (sources == null || sources.isEmpty()) {
            throw new IOException("Template [" + templateId + "] declares no sources.");
        }
        return sources;
    }

    /**
     * Reads the model file.
     *
     * @param projectObject the project
     * @param workspace the workspace name
     * @param project the project name
     * @param path the project-relative path
     * @return the model file's content
     * @throws IOException when the model file does not exist
     */
    private static String readModel(Project projectObject, String workspace, String project, String path) throws IOException {
        File model = projectObject.getFile(path);
        if (model == null || !model.exists()) {
            throw new IOException(
                    "Model file [" + path + "] does not exist in project [" + project + "] in workspace [" + workspace + "].");
        }
        return new String(model.getContent(), StandardCharsets.UTF_8);
    }

    /**
     * Folds in the entity extensions other projects contribute to this model.
     *
     * <p>
     * Another project may contribute an extension entity that adds fields to one of this model's
     * entities - a localisation module adding a national identifier to an employee, say. Such a
     * contribution cannot rewrite this model at authoring time, so it is folded in at generation time:
     * every sibling project's model is scanned for extensions naming this project, and they are
     * appended to this model's entity list for the generator to merge. They are sorted so that the
     * merged column order is reproducible across regenerations.
     *
     * @param modelText the model file's content
     * @param workspaceObject the workspace
     * @param project the project name
     * @return the model, with the contributed extensions appended
     */
    private static String augmentWithExtensions(String modelText, Workspace workspaceObject, String project) {
        Map<String, Object> root = ModelJson.parseObject(modelText);
        Map<String, Object> model = asMap(root.get("model"));
        if (model == null || !(model.get("entities") instanceof List)) {
            return modelText;
        }
        List<Map<String, Object>> extensions = new ArrayList<>();
        for (Project sibling : workspaceObject.getProjects()) {
            String siblingName = sibling.getName();
            if (siblingName.equals(project)) {
                continue; // an entity is not extended from within its own project
            }
            File siblingModel = sibling.getFile(siblingName + ".model");
            if (siblingModel == null || !siblingModel.exists()) {
                continue;
            }
            Map<String, Object> siblingModelRoot;
            try {
                siblingModelRoot = asMap(ModelJson.parseObject(new String(siblingModel.getContent(), StandardCharsets.UTF_8))
                                                  .get("model"));
            } catch (RuntimeException e) {
                logger.debug("Skipping project [{}] while collecting entity extensions: its model does not parse",
                        sanitizeForLog(siblingName), e);
                continue;
            }
            if (siblingModelRoot == null) {
                continue;
            }
            for (Map<String, Object> entity : asMaps(siblingModelRoot.get("entities"))) {
                if ("EXTENSION".equals(str(entity, "type")) && project.equals(str(entity, "extensionReferencedModel"))) {
                    extensions.add(entity);
                }
            }
        }
        if (extensions.isEmpty()) {
            return modelText;
        }
        extensions.sort((left, right) -> (str(left, "extensionReferencedEntity") + "." + str(left, "name")).compareTo(
                str(right, "extensionReferencedEntity") + "." + str(right, "name")));
        List<Object> entities = ModelValues.asList(model.get("entities"));
        entities.addAll(extensions);
        return JavaScriptJson.compact(root);
    }

    /**
     * Clears the generation subfolders this run writes into, derived from the output paths.
     *
     * <p>
     * Only the subfolders actually written are cleared. The standard templates all write under the
     * model file's own folder, for which this is no different from clearing that one folder - but a
     * template that targets a sibling folder, as the process glue does, must not wipe another
     * template's output for the same model.
     *
     * @param projectObject the project
     * @param project the project name
     * @param generated the rendered files
     */
    private void clearGenerationFolders(Project projectObject, String project, List<GeneratedFile> generated) {
        Set<String> subfolders = new LinkedHashSet<>();
        for (GeneratedFile file : generated) {
            String path = file.path();
            if (path == null || !path.startsWith(GENERATION_FOLDER + "/")) {
                continue;
            }
            String rest = path.substring(GENERATION_FOLDER.length() + 1);
            int slash = rest.indexOf('/');
            String subfolder = slash >= 0 ? rest.substring(0, slash) : rest;
            if (!subfolder.isEmpty()) {
                subfolders.add(subfolder);
            }
        }
        Folder generationFolder = projectObject.getFolder(GENERATION_FOLDER);
        if (generationFolder == null || !generationFolder.exists()) {
            return;
        }
        for (String subfolder : subfolders) {
            if (generationFolder.existsFolder(subfolder)) {
                generationFolder.deleteFolder(subfolder);
                publisherService.unpublish(project + "/" + GENERATION_FOLDER + "/" + subfolder);
            }
        }
    }

    /**
     * Writes one generated file, creating the folders leading to it.
     *
     * @param projectObject the project
     * @param path the project-relative path
     * @param content the content
     * @return the written file
     */
    private static File write(Project projectObject, String path, String content) {
        return projectObject.createFile(path, content.getBytes(StandardCharsets.UTF_8));
    }

    /**
     * Resolves a workspace.
     *
     * @param workspace the workspace name
     * @return the workspace
     * @throws IOException when it does not exist
     */
    private Workspace requireWorkspace(String workspace) throws IOException {
        Workspace workspaceObject = workspaceService.getWorkspace(workspace);
        if (workspaceObject == null || !workspaceObject.exists()) {
            throw new IOException("Workspace [" + workspace + "] does not exist.");
        }
        return workspaceObject;
    }

    /**
     * Resolves a project.
     *
     * @param workspaceObject the workspace
     * @param workspace the workspace name
     * @param project the project name
     * @return the project
     * @throws IOException when it does not exist
     */
    private static Project requireProject(Workspace workspaceObject, String workspace, String project) throws IOException {
        Project projectObject = workspaceObject.getProject(project);
        if (projectObject == null || !projectObject.exists()) {
            throw new IOException("Project [" + project + "] does not exist in workspace [" + workspace + "].");
        }
        return projectObject;
    }


    /**
     * Strip CR/LF (and stray control characters) from a value that arrives in a user-controlled URL
     * segment before it reaches the log, so a crafted request cannot forge log entries.
     *
     * @param value the value
     * @return the value, with anything that could break a log line replaced
     */
    private static String sanitizeForLog(String value) {
        if (value == null) {
            return "null";
        }
        return value.replaceAll("[\\r\\n\\t]", "_");
    }

}
