/*
 * Copyright (c) 2010-2026 Eclipse Dirigible contributors
 *
 * All rights reserved. This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: Eclipse Dirigible contributors SPDX-License-Identifier: EPL-2.0
 */
package org.eclipse.dirigible.integration.tests.api;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.both;
import static org.hamcrest.Matchers.greaterThanOrEqualTo;
import static org.hamcrest.Matchers.lessThan;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicReference;

import org.eclipse.dirigible.components.initializers.synchronizer.SynchronizationProcessor;
import org.eclipse.dirigible.repository.api.IRepository;
import org.eclipse.dirigible.repository.api.IRepositoryStructure;
import org.eclipse.dirigible.repository.api.IResource;
import org.eclipse.dirigible.tests.base.IntegrationTest;
import org.eclipse.dirigible.tests.framework.restassured.RestAssuredExecutor;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;

/**
 * dirigible #7547: {@code whenTargetDeleted: restrict} on a <b>cross-model</b> to-one refuses the
 * target's delete while a record of the referencing model still points at it.
 *
 * <p>
 * The issue's second reproduction: an employee referenced by another module's expense claims was
 * deleted with a 200, and the claims went on pointing at a missing employee. The employee's
 * repository is generated by its own model and cannot know who references it, so the REFERENCING
 * repository contributes an {@code org.eclipse.dirigible.sdk.db.DeleteRestrictor} and every delete
 * asks all of them.
 *
 * <ol>
 * <li><b>Generation</b> - the consumer's repository implements the extension point and counts only
 * the relation that declares the restriction.</li>
 * <li><b>Runtime</b> - the owner's delete of a referenced employee is answered 409 naming the
 * referencing records and their count; an employee referenced only through a relation that declares
 * nothing is deleted; once the reference is gone, so is the refusal.</li>
 * </ol>
 */
class IntentCrossModelDeleteRestrictIT extends IntegrationTest {

    private static final String WORKSPACE = "workspace";
    /** Owns the referenced master data. Its project name differs from the model alias on purpose. */
    private static final String OWNER = "restrict-owner";
    /** References the owner's Employee twice - once restricting its delete, once not. */
    private static final String CONSUMER = "restrict-consumer";

    private static final String OWNER_MODEL = "staff";
    private static final String CONSUMER_MODEL = "claims";

    private static final String OWNER_INTENT = """
            name: staff
            description: cross-model restrict fixture - the owner of the referenced master data

            entities:
              - name: Employee
                fields:
                  - { name: id,   type: integer, primaryKey: true, generated: true }
                  - { name: name, type: string,  required: true, length: 100 }
            """;

    private static final String CONSUMER_INTENT = """
            name: claims
            description: cross-model restrict fixture - a claim keeps the employee it was raised by

            uses:
              - { model: staff, project: restrict-owner }

            entities:
              - name: ExpenseClaim
                fields:
                  - { name: id,     type: integer, primaryKey: true, generated: true }
                  - { name: amount, type: decimal }
                relations:
                  - { name: Employee, kind: manyToOne, to: Employee, model: staff, required: true, whenTargetDeleted: restrict }
                  - { name: Reviewer, kind: manyToOne, to: Employee, model: staff }
            """;

    private static final String REFUSAL = "This Employee is referenced by 1 Expense Claim record(s) and cannot be deleted";

    @Autowired
    private IRepository repository;
    @Autowired
    private RestAssuredExecutor restAssuredExecutor;
    @Autowired
    private SynchronizationProcessor synchronizationProcessor;

    @Test
    void a_cross_model_reference_restricts_the_targets_delete() {
        writeIntent(OWNER, OWNER_INTENT);
        generateProject(OWNER);
        writeIntent(CONSUMER, CONSUMER_INTENT);
        generateProject(CONSUMER);

        assertTheConsumerContributesTheRestriction();

        publishProject(OWNER);
        publishProject(CONSUMER);
        synchronizationProcessor.forceProcessSynchronizers();

        assertTheReferencedEmployeeCannotBeDeleted();
    }

    /**
     * Layer 1: the referencing repository is the contribution, and it counts the restricting relation
     * only.
     */
    private void assertTheConsumerContributesTheRestriction() {
        String claimRepository = contentOf(CONSUMER, "gen/" + CONSUMER_MODEL + "/data/expenseclaim/ExpenseClaimRepository.java");
        assertTrue(claimRepository.contains("implements org.eclipse.dirigible.sdk.db.DeleteRestrictor"),
                "the referencing repository must contribute to the delete-restriction extension point: " + claimRepository);
        assertTrue(
                claimRepository.contains("EmployeeEntity\".equals(targetEntity)")
                        && claimRepository.contains(".eq(\"Employee\", targetId)"),
                "it must count the claims referencing the owner's Employee through the restricting relation: " + claimRepository);
        assertFalse(claimRepository.contains(".eq(\"Reviewer\", targetId)"), "a relation that declares nothing must restrict nothing");
    }

    /** Layer 2 - the promise: a referenced employee stays, an unreferenced one goes. */
    private void assertTheReferencedEmployeeCannotBeDeleted() {
        String ownerApi = "/services/java/" + OWNER + "/gen/" + OWNER_MODEL + "/api";
        String consumerApi = "/services/java/" + CONSUMER + "/gen/" + CONSUMER_MODEL + "/api";
        String employees = ownerApi + "/employee/EmployeeController";
        String claims = consumerApi + "/expenseclaim/ExpenseClaimController";

        int ada = create(employees, "{\"Name\":\"Ada\"}");
        int bob = create(employees, "{\"Name\":\"Bob\"}");
        int claim = create(claims, "{\"Employee\":" + ada + ",\"Reviewer\":" + bob + ",\"Amount\":12.5}");

        restAssuredExecutor.execute(() -> {
            String body = given().when()
                                 .delete(employees + "/" + ada)
                                 .then()
                                 .statusCode(409)
                                 .extract()
                                 .asString();
            assertTrue(body.contains(REFUSAL), "the 409 must name the referencing records and their count; got: " + body);
        });
        restAssuredExecutor.execute(() -> given().when()
                                                 .get(employees + "/" + ada)
                                                 .then()
                                                 .statusCode(200));

        // Bob is referenced only as a reviewer, which declares no restriction.
        restAssuredExecutor.execute(() -> given().when()
                                                 .delete(employees + "/" + bob)
                                                 .then()
                                                 .statusCode(both(greaterThanOrEqualTo(200)).and(lessThan(300))));

        // With the claim gone, nothing references Ada any more.
        restAssuredExecutor.execute(() -> given().when()
                                                 .delete(claims + "/" + claim)
                                                 .then()
                                                 .statusCode(both(greaterThanOrEqualTo(200)).and(lessThan(300))));
        restAssuredExecutor.execute(() -> given().when()
                                                 .delete(employees + "/" + ada)
                                                 .then()
                                                 .statusCode(both(greaterThanOrEqualTo(200)).and(lessThan(300))));
    }

    private int create(String controller, String body) {
        AtomicInteger id = new AtomicInteger();
        restAssuredExecutor.execute(() -> id.set(given().contentType("application/json")
                                                        .body(body)
                                                        .when()
                                                        .post(controller)
                                                        .then()
                                                        .statusCode(200)
                                                        .extract()
                                                        .path("Id")),
                60);
        return id.get();
    }

    /**
     * Generate the model files from the intent and drive model-to-code from the generate response's own
     * plan.
     */
    private void generateProject(String project) {
        AtomicReference<List<Map<String, Object>>> plan = new AtomicReference<>();
        restAssuredExecutor.execute(() -> plan.set(given().when()
                                                          .post("/services/ide/intent/generate?workspace=" + WORKSPACE + "&project="
                                                                  + project + "&path=app.intent")
                                                          .then()
                                                          .statusCode(200)
                                                          .extract()
                                                          .jsonPath()
                                                          .getList("codeGenerations")));
        for (Map<String, Object> codeGeneration : plan.get()) {
            assertEquals(Boolean.TRUE, codeGeneration.get("generated"),
                    "generating code from " + codeGeneration.get("path") + " failed: " + codeGeneration.get("error"));
        }
    }

    private void publishProject(String project) {
        restAssuredExecutor.execute(() -> given().when()
                                                 .post("/services/ide/publisher/" + WORKSPACE + "/" + project + "/")
                                                 .then()
                                                 .statusCode(200));
    }

    private void writeIntent(String project, String yaml) {
        String path = projectPath(project) + "/app.intent";
        IResource existing = repository.getResource(path);
        if (existing.exists()) {
            existing.setContent(yaml.getBytes(StandardCharsets.UTF_8));
        } else {
            repository.createResource(path, yaml.getBytes(StandardCharsets.UTF_8));
        }
    }

    private String contentOf(String project, String fileName) {
        return new String(repository.getResource(projectPath(project) + "/" + fileName)
                                    .getContent(),
                StandardCharsets.UTF_8);
    }

    private static String projectPath(String project) {
        return IRepositoryStructure.PATH_USERS + "/admin/" + WORKSPACE + "/" + project;
    }

    @AfterEach
    void cleanup() {
        for (String project : List.of(CONSUMER, OWNER)) {
            restAssuredExecutor.execute(() -> given().when()
                                                     .delete("/services/ide/publisher/" + WORKSPACE + "/" + project)
                                                     .then()
                                                     .statusCode(both(greaterThanOrEqualTo(200)).and(lessThan(300))));
            if (repository.hasCollection(projectPath(project))) {
                repository.removeCollection(projectPath(project));
            }
        }
    }
}
