/*
 * Copyright (c) 2010-2026 Eclipse Dirigible contributors
 *
 * All rights reserved. This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: Eclipse Dirigible contributors SPDX-License-Identifier: EPL-2.0
 */
package org.eclipse.dirigible.components.intent.generator;

import java.util.LinkedHashSet;
import java.util.Set;

import org.eclipse.dirigible.components.intent.model.IntentModel;
import org.eclipse.dirigible.components.intent.model.ProcessIntent;

/**
 * Shared reading of a process's {@code trigger} block: {@code trigger: {
 * onCreate|onUpdate|onDelete: <Entity>, when: "<expr>" }} means "start this process when an
 * instance of {@code <Entity>} fires that lifecycle event (optionally only when the guard holds)".
 * The model-layer effect is that the entity gains a {@code ProcessId} back-reference field; the
 * runtime listener is generated by the Glue-Code template (binding the entity's per-operation
 * topic; see {@link EventBinding}).
 */
public final class TriggerSupport {

    private TriggerSupport() {}

    /** The entity named by a process's {@code trigger}, or null when there is no trigger. */
    public static String triggerEntity(ProcessIntent process) {
        return EventBinding.entity(process.getTrigger());
    }

    /**
     * The lifecycle event kind the process triggers on
     * ({@code onCreate}/{@code onUpdate}/{@code onDelete}), or null.
     */
    public static String triggerKind(ProcessIntent process) {
        return EventBinding.kind(process.getTrigger());
    }

    /** The optional {@code when} guard expression on the trigger, or null. */
    public static String triggerWhen(ProcessIntent process) {
        Object value = process.getTrigger()
                              .get("when");
        return value == null ? null : value.toString();
    }

    /**
     * The optional {@code businessKey} field flagged on the trigger - the trigger entity field whose
     * value becomes the started process instance's BPM business key. Null when omitted, in which case
     * the generator defaults the business key to the entity's primary key.
     */
    public static String triggerBusinessKey(ProcessIntent process) {
        Object value = process.getTrigger()
                              .get("businessKey");
        return value == null ? null : value.toString();
    }

    /**
     * The optional {@code businessKeyStrategy} on the trigger - how the {@code businessKey} field is
     * populated when blank. Today the only strategy is {@code timestamp} (a {@code yyyyMMddHHmmss}
     * value minted by the listener). Null when the field is used as-is.
     */
    public static String triggerBusinessKeyStrategy(ProcessIntent process) {
        Object value = process.getTrigger()
                              .get("businessKeyStrategy");
        return value == null ? null : value.toString();
    }

    /**
     * Entity names that some process triggers on - they get the {@code ProcessId} back-reference,
     * regardless of which lifecycle event starts the process.
     */
    public static Set<String> triggerTargetEntities(IntentModel model) {
        Set<String> targets = new LinkedHashSet<>();
        for (ProcessIntent process : model.getProcesses()) {
            String entity = triggerEntity(process);
            if (entity != null && !entity.isBlank()) {
                targets.add(entity);
            }
        }
        return targets;
    }
}
