/*
 * Copyright (c) 2010-2026 Eclipse Dirigible contributors
 *
 * All rights reserved. This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: Eclipse Dirigible contributors SPDX-License-Identifier: EPL-2.0
 */
package org.eclipse.dirigible.components.intent.generator;

import java.util.LinkedHashSet;
import java.util.Set;

import org.eclipse.dirigible.components.intent.model.IntentModel;
import org.eclipse.dirigible.components.intent.model.ProcessIntent;

/**
 * Shared reading of a process's {@code trigger} block. Today only {@code onCreate} is modelled:
 * {@code trigger: { onCreate: <Entity> }} on a process means "start this process when an instance
 * of {@code <Entity>} is created". The model-layer effect is that the entity gains a
 * {@code ProcessId} back-reference field; the runtime wiring (the {@code .listener} + handler under
 * {@code gen/events} and the DAO event publish) is generated by the language templates as a later
 * step.
 */
public final class TriggerSupport {

    private TriggerSupport() {}

    /** The entity named by a process's {@code trigger: { onCreate: <Entity> }}, or null when absent. */
    public static String onCreateEntity(ProcessIntent process) {
        Object value = process.getTrigger()
                              .get("onCreate");
        return value == null ? null : value.toString();
    }

    /**
     * Entity names that some process starts on create - they get the {@code ProcessId} back-reference.
     */
    public static Set<String> onCreateTargetEntities(IntentModel model) {
        Set<String> targets = new LinkedHashSet<>();
        for (ProcessIntent process : model.getProcesses()) {
            String entity = onCreateEntity(process);
            if (entity != null && !entity.isBlank()) {
                targets.add(entity);
            }
        }
        return targets;
    }
}
