/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
export const getTemplate = () => ({
  name: "Message Listener (Java)",
  description: "Message Listener with a client Java handler",
  sources: [
    {
      location: "/template-listener/handler.java.template",
      action: "generate",
      rename: "{{javaPackageName}}/{{javaClassName}}.java",
    },
    {
      location: "/template-listener/trigger.java.template",
      action: "generate",
      rename: "{{javaPackageName}}/{{javaClassName}}Trigger.java",
    },
  ],
  parameters: [],
  order: 51,
});
