# Buildpacks to include in builder
[[buildpacks]]
uri = "."

[[order]]
    [[order.group]]
    id = "dirigiblelabs/buildpacks-dirigible-kyma"
    version = "#{DirigibleVersion}#"

[stack]
id = "org.eclipse.dirigible"
build-image = "dirigiblelabs/buildpacks-stack-build-dirigible-kyma:#{DirigibleVersion}#"
run-image = "dirigiblelabs/buildpacks-stack-run-dirigible-kyma:#{DirigibleVersion}#"
