/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
export const getTemplate = () => ({
  name: "Database Access (API)",
  description: "Client Java Service With Database Query Support",
  glyph: "sap-icon--database",
  sources: [
    {
      location: "/template-database-access/service.java.template",
      action: "generate",
      rename: "{{javaPackageName}}/{{javaClassName}}.java",
    },
  ],
  parameters: [],
  order: 21,
});
