{
 "title": "Meters",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Flowable completed process instances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "flowable_completedProcessInstanceCount",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Micrometer calls counter total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "micrometer_calls_counter_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "OTEL counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "otel_calls_counter_total", "legendFormat": "__auto" }
   ]
  }
 ]
}