apiVersion: kpack.io/v1alpha1
kind: ClusterStore
metadata:
  name: dirigible-store
spec:
  sources:
  - image: dirigiblelabs/buildpacks-dirigible-kyma:<tag>
---
apiVersion: kpack.io/v1alpha1
kind: ClusterStack
metadata:
  name: dirigible-stack
spec:
  id: org.eclipse.dirigible
  buildImage:
    image: dirigiblelabs/buildpacks-stack-build-dirigible-kyma:<tag>
  runImage:
    image: dirigiblelabs/buildpacks-stack-run-dirigible-kyma:<tag>
---
apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: dirigible-builder
spec:
  serviceAccount: docker-registry-service-account
  tag: dirigiblelabs/dirigible-builder:<tag>
  stack:
    name: dirigible-stack
    kind: ClusterStack
  store:
    name: dirigible-store
    kind: ClusterStore
  order:
  - group:
    - id: dirigiblelabs/buildpacks-dirigible-kyma
