/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
import * as schemaTemplateManager from "template-application-schema/template/template";
import * as restTemplateManager from "template-application-rest-java/template/template";
import * as uiTemplate from "template-application-ui-harmonia-java/template/ui/template";
import * as generateUtils from "service-generate/template/generateUtils";
import * as parameterUtils from "service-generate/template/parameterUtils";

export function generate(model, parameters) {
    model = JSON.parse(model).model;
    let templateSources = getTemplate(parameters).sources;
    parameters.javaRuntime = true;
    parameterUtils.process(model, parameters)
    // App caption for the shell (title + sidebar header): prefer the model-level title/description
    // (the intent's humanised name + description) over the bare project name.
    parameters.appTitle = (model.title && String(model.title).trim()) ? model.title : parameters.projectName;
    parameters.appDescription = model.description || '';
    // Brand icon (a Lucide icon name) for the shell header: an explicit generate-time parameter wins,
    // else the model-level icon (the intent's `icon`), else a neutral default.
    parameters.appIcon = (parameters.appIcon && String(parameters.appIcon).trim()) ? String(parameters.appIcon).trim()
        : ((model.icon && String(model.icon).trim()) ? String(model.icon).trim() : 'blocks');
    return generateUtils.generateFiles(model, parameters, templateSources);
};

export function getTemplate(parameters) {
    // The database schema (.table/.schema artefacts) is REQUIRED: it is what actually creates the
    // physical tables (TableCreateProcessor). The client-Java layer only maps an @Entity to an
    // existing table (JavaEntityManager registers, it does not CREATE), so without the schema a
    // freshly-generated app has no tables and CRUD / CSVIM seeds fail. The AngularJS full-stack
    // template includes the schema for the same reason.
    let schemaTemplate = schemaTemplateManager.getTemplate(parameters);
    let restTemplate = restTemplateManager.getTemplate(parameters);

    let templateSources = [
        ...schemaTemplate.sources,
        ...restTemplate.sources,
        ...uiTemplate.getSources(parameters)
    ];

    let templateParameters = getTemplateParameters()
        .concat(schemaTemplate.parameters)
        .concat(restTemplate.parameters);
    // Dedupe shared parameters (tablePrefix, dataSource, …) by name so the Generate dialog shows each once.
    const seenParameterNames = new Set();
    templateParameters = templateParameters.filter(p => {
        if (!p || seenParameterNames.has(p.name)) return false;
        seenParameterNames.add(p.name);
        return true;
    });

    return {
        name: "Application - UI (Harmonia) - Java",
        description: "Application With UI (Alpine.js + Harmonia SPA), Java REST APIs and DAOs",
        extension: "model",
        sources: templateSources,
        parameters: templateParameters
    };
};

function getTemplateParameters() {
    return [
        {
            name: "brand",
            label: "Brand",
            placeholder: "Enter Brand"
        },
        {
            name: "brandUrl",
            label: "Brand URL",
            placeholder: "Enter Brand URL"
        },
        {
            name: "title",
            label: "Title",
            placeholder: "Enter Title"
        },
        {
            name: "appIcon",
            label: "Brand Icon",
            placeholder: "Lucide icon name (e.g. book); defaults to the intent icon or 'blocks'"
        },
        {
            name: "description",
            label: "Description",
            placeholder: "Enter Description"
        }
    ];
}
