/*
 * Copyright (c) 2010-2026 Eclipse Dirigible contributors
 *
 * All rights reserved. This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: Eclipse Dirigible contributors SPDX-License-Identifier: EPL-2.0
 */
package org.eclipse.dirigible.sdk.db;

/**
 * Extension point through which records restrict the delete of a record they reference, when the
 * two are generated by different models (intent {@code whenTargetDeleted: restrict} on a
 * cross-model relation).
 *
 * <p>
 * The referenced entity's repository cannot know which other models point at it - they may be
 * generated later, or by another team - so the REFERENCING side contributes: its generated
 * repository implements this interface, and every repository asks all contributions before it
 * deletes, refusing with {@link DeleteRestrictionException} while any of them still counts a
 * reference. A contribution is a {@code @Component} bean like any other extension, found through
 * {@link org.eclipse.dirigible.sdk.extensions.Extensions#find(Class)}.
 */
public interface DeleteRestrictor {

    /**
     * How many of this contribution's records still reference the given record.
     *
     * @param targetEntity the fully qualified class name of the entity being deleted
     * @param targetId the primary key of the record being deleted
     * @return the number of referencing records; {@code 0} when there are none, or when this
     *         contribution does not reference {@code targetEntity} at all
     */
    int countReferencing(String targetEntity, Object targetId);

    /**
     * How a refusal names the referencing records, as a person reading the page knows them.
     *
     * @return the referencing entity's label, e.g. {@code Expense Claim}
     */
    String referencingLabel();
}
