/*
 * Copyright (c) 2010-2026 Eclipse Dirigible contributors
 *
 * All rights reserved. This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: Eclipse Dirigible contributors SPDX-License-Identifier: EPL-2.0
 */
package org.eclipse.dirigible.integration.tests.ui.tests;

import org.eclipse.dirigible.tests.base.BaseTestProject;
import org.eclipse.dirigible.tests.base.ProjectUtil;
import org.eclipse.dirigible.tests.framework.browser.Browser;
import org.eclipse.dirigible.tests.framework.browser.HtmlAttribute;
import org.eclipse.dirigible.tests.framework.browser.HtmlElementType;
import org.eclipse.dirigible.tests.framework.ide.EdmView;
import org.eclipse.dirigible.tests.framework.ide.IDE;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Component;

/**
 * Harmonia+Java counterpart of {@link DependsOnTestProject}. It exercises exactly the same "Depends
 * On" scenario (a City dropdown that is filtered by the selected Country), but against the modern
 * Alpine.js + Harmonia SPA generated by the {@code template-application-ui-harmonia-java}
 * full-stack template instead of the legacy AngularJS dashboard. The only difference from the
 * AngularJS fixture is the {@code templateId} in {@code edm.gen}; the model, data and depends-on
 * metadata are identical.
 */
@Lazy
@Component
class DependsOnHarmoniaTestProject extends BaseTestProject {

    private static final String EDM_FILE_NAME = "edm.edm";
    private static final String PROJECT_RESOURCES_PATH = "DependsOnHarmoniaIT";

    // The Harmonia SPA entry (per-project shell), hash-routed by Pinecone. Open the Orders create
    // route directly to avoid the dashboard's ambiguous entity tiles.
    private static final String ORDERS_LIST_URI = "/services/web/DependsOnHarmoniaIT/gen/edm/index.html#/Orders";

    private final Browser browser;

    DependsOnHarmoniaTestProject(IDE ide, ProjectUtil projectUtil, EdmView edmView, Browser browser) {
        super(PROJECT_RESOURCES_PATH, ide, projectUtil, edmView);
        this.browser = browser;
    }

    @Override
    public void configure() {
        copyToWorkspace();
        generateEDM(EDM_FILE_NAME);
        publish();
    }

    @Override
    public void verify() {
        browser.openPath(ORDERS_LIST_URI);

        // Open the Orders create form via the list toolbar's primary "New" button (the Harmonia
        // equivalent of the AngularJS "Create" button).
        browser.clickOnElementWithText(HtmlElementType.BUTTON, "New");

        // The form caption is the entity's human label - assert it resolved to a real value and not
        // the literal "${ENTITYLABEL}" (the depends-on entities are hand-authored, so they carry no
        // baked entityLabel; the generator must derive it). The caption no longer force-uppercases
        // (title styling unified with the document layout in #6361), so the resolved label is "Orders".
        browser.assertElementExistsByTypeAndContainsText(HtmlElementType.SPAN, "Orders");

        // Pick Country = Bulgaria. The Harmonia x-h-select hides the bound <input id="f_Country">
        // and renders a visible <span role="combobox"> trigger whose text is the placeholder; click
        // that trigger, then the option (a div[role="option"] whose text is the label).
        browser.clickOnElementByAttributePatternAndText(HtmlElementType.SPAN, HtmlAttribute.ROLE, "combobox", "Select Country...");
        browser.clickOnElementByAttributePatternAndText(HtmlElementType.DIV, HtmlAttribute.ROLE, "option", "Bulgaria");

        // The selection now shows on the Country trigger - this is also what fires the depends-on
        // watcher that re-filters the City options.
        browser.assertElementExistByAttributePatternAndText(HtmlElementType.SPAN, HtmlAttribute.ROLE, "combobox", "Bulgaria");

        // City depends on Country: opening it now must offer only Bulgaria's cities.
        browser.clickOnElementByAttributePatternAndText(HtmlElementType.SPAN, HtmlAttribute.ROLE, "combobox", "Select City...");
        browser.assertElementExistsByTypeAndContainsText(HtmlElementType.SPAN, "Sofia");
        browser.assertElementExistsByTypeAndContainsText(HtmlElementType.SPAN, "Varna");
        browser.assertElementDoesNotExistsByTypeAndContainsText(HtmlElementType.SPAN, "Milano");
    }
}
