/*
 * Copyright (c) 2010-2026 Eclipse Dirigible contributors
 *
 * All rights reserved. This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: Eclipse Dirigible contributors SPDX-License-Identifier: EPL-2.0
 */
package org.eclipse.dirigible.integration.tests.ui.tests;

import io.restassured.http.ContentType;
import org.eclipse.dirigible.components.base.helpers.JsonHelper;
import org.eclipse.dirigible.tests.base.BaseMultitenantTestProject;
import org.eclipse.dirigible.tests.base.ProjectUtil;
import org.eclipse.dirigible.tests.framework.browser.Browser;
import org.eclipse.dirigible.tests.framework.browser.BrowserFactory;
import org.eclipse.dirigible.tests.framework.browser.HtmlElementType;
import org.eclipse.dirigible.tests.framework.ide.EdmView;
import org.eclipse.dirigible.tests.framework.ide.IDE;
import org.eclipse.dirigible.tests.framework.ide.IDEFactory;
import org.eclipse.dirigible.tests.framework.restassured.RestAssuredExecutor;
import org.eclipse.dirigible.tests.framework.tenant.DirigibleTestTenant;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Lazy;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Component;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.hasSize;

/**
 * Harmonia+Java counterpart of {@link MultitenancyITTestProject}. It verifies the same per-tenant
 * isolation, but the entity application is generated by
 * {@code template-application-ui-harmonia-java} (Java REST + DAOs + Alpine/Harmonia SPA) instead of
 * the AngularJS/TypeScript full-stack.
 * <p>
 * The stack-agnostic checks are unchanged (a hand-authored TS view service, an OData entity, a CMIS
 * documents service - none of which are generated by the app template). The one stack-specific
 * check targets the generated <b>Java</b> {@code BookController} instead of the TypeScript
 * {@code BookService.ts}, and the per-tenant home page is the Harmonia SPA instead of the AngularJS
 * dashboard.
 * <p>
 * NOTE: the AngularJS fixture's job + listener checks are intentionally NOT ported. Both handlers
 * consumed the <i>TypeScript-generated</i> {@code BookRepository} DAO, which the Java template does
 * not emit; reproducing them would mean rewriting the handlers as client-Java against the Java DAO.
 * Job/listener behaviour under multitenancy is exercised by the dedicated job/listener ITs.
 */
@Lazy
@Component
class MultitenancyHarmoniaITTestProject extends BaseMultitenantTestProject {

    private static final Logger LOGGER = LoggerFactory.getLogger(MultitenancyHarmoniaITTestProject.class);

    private static final String PROJECT_RESOURCES_PATH = "MultitenancyHarmoniaIT";
    // The Harmonia SPA home (per-project shell), replacing the AngularJS /services/web/dashboard.
    private static final String UI_HOME_PATH = "/services/web/" + PROJECT_RESOURCES_PATH + "/gen/edm/index.html";
    private static final String TS_BASE_PATH = "/services/ts/" + PROJECT_RESOURCES_PATH + "/";
    private static final String READERS_VIEW_SERVICE_PATH = TS_BASE_PATH + "views/ReaderViewService.ts";
    private static final String DOCUMENTS_SERVICE_PATH = TS_BASE_PATH + "cmis/DocumentService.ts/documents";
    // The generated Java REST controller (rest-java): <restBase>/<javaPerspective>/<Entity>Controller.
    // The Book entity's perspective "Books" sanitises to the lower-case package segment "books".
    private static final String BOOKS_SERVICE_PATH = "/services/java/" + PROJECT_RESOURCES_PATH + "/gen/edm/api/books/BookController";
    private static final String READERS_ODATA_ENTITY_PATH = "/odata/v2/Readers";

    private final BrowserFactory browserFactory;
    private final RestAssuredExecutor restAssuredExecutor;
    private final IDEFactory ideFactory;

    MultitenancyHarmoniaITTestProject(BrowserFactory browserFactory, EdmView edmView, RestAssuredExecutor restAssuredExecutor,
            IDEFactory ideFactory, ProjectUtil projectUtil) {
        super(PROJECT_RESOURCES_PATH, ideFactory.create(), projectUtil, edmView);
        this.browserFactory = browserFactory;
        this.restAssuredExecutor = restAssuredExecutor;
        this.ideFactory = ideFactory;
    }

    @Override
    public void configure() {
        copyToWorkspace();
        generateEDM("edm.edm");
        publish();
    }

    @Override
    public void verify(DirigibleTestTenant tenant) {
        LOGGER.info("Verifying test project for tenant [{}]...", tenant);

        wrapVerification(this::verifyHomePageAccessibleByTenant, tenant, "verifyHomePageAccessibleByTenant");
        wrapVerification(this::verifyView, tenant, "verifyView");
        wrapVerification(this::verifyEdmGeneratedResources, tenant, "verifyEdmGeneratedResources");
        wrapVerification(this::verifyOData, tenant, "verifyOData");
        wrapVerification(this::verifyDocumentsAPI, tenant, "verifyDocumentsAPI");

        LOGGER.info("Test project for tenant [{}] has been verified successfully!", tenant);
    }

    private void verifyHomePageAccessibleByTenant(DirigibleTestTenant tenant) {
        Browser browser = browserFactory.createByHost(tenant.getHost());
        browser.openPath(UI_HOME_PATH);

        IDE ide = ideFactory.create(browser, tenant.getUsername(), tenant.getPassword());
        boolean forceLogin = !tenant.isDefaultTenant();
        ide.login(forceLogin);

        // The Harmonia shell renders a "Dashboard" entry in its Application sidebar group.
        browser.assertElementExistsByTypeAndContainsText(HtmlElementType.SPAN, "Dashboard");
    }

    /**
     * Verifies indirectly:<br>
     * - MultitenancyHarmoniaIT/views/readers.view is created and it is working<br>
     * - MultitenancyHarmoniaIT/csvim/data.csvim is imported <br>
     * - default DB datasource is resolved correctly
     */
    private void verifyView(DirigibleTestTenant tenant) {
        restAssuredExecutor.execute(tenant, //
                () -> given().when()
                             .get(READERS_VIEW_SERVICE_PATH)
                             .then()
                             .statusCode(200)
                             .body("$", hasSize(2))
                             .body("[0].READER_FIRST_NAME", equalTo("Ivan"))
                             .body("[0].READER_LAST_NAME", equalTo("Ivanov"))
                             .body("[1].READER_FIRST_NAME", equalTo("Maria"))
                             .body("[1].READER_LAST_NAME", equalTo("Petrova")),
                25);
    }

    /**
     * Verifies indirectly:<br>
     * - the generated schema is created<br>
     * - the generated <b>Java</b> REST controller is created and it works<br>
     * - default DB datasource is resolved correctly, isolated per tenant
     */
    private void verifyEdmGeneratedResources(DirigibleTestTenant tenant) {
        restAssuredExecutor.execute(tenant, () -> verifyBookREST(tenant));
    }

    private void verifyBookREST(DirigibleTestTenant tenant) {
        String title = "Title[" + tenant.getName() + "]";
        String author = "Author[" + tenant.getName() + "]";
        String jsonPayload = String.format("""
                {
                    "Title": "%s",
                    "Author": "%s"
                }
                """, title, author);

        // The generated Java REST controller's create returns 200 (repository.save), unlike the
        // TypeScript BookService.ts which returned 201.
        given().contentType(ContentType.JSON)
               .body(jsonPayload)
               .when()
               .post(BOOKS_SERVICE_PATH)
               .then()
               .statusCode(200);

        given().when()
               .get(BOOKS_SERVICE_PATH)
               .then()
               .statusCode(200)
               .body("$", hasSize(1))
               .body("[0].Id", equalTo(1))
               .body("[0].Title", equalTo(title))
               .body("[0].Author", equalTo(author));
    }

    private void verifyDocumentsAPI(DirigibleTestTenant tenant) {
        restAssuredExecutor.execute(tenant, () -> {
            given().when()
                   .get(DOCUMENTS_SERVICE_PATH)
                   .then()
                   .statusCode(200)
                   .body("$", hasSize(0));

            String documentName = "DOC_NAME_" + tenant.getId() + ".txt";
            String documentContent = "DOC_CONTENT_" + tenant.getId();
            String jsonPayload = String.format("""
                    {
                        "documentName": "%s",
                        "content": "%s"
                    }
                    """, documentName, documentContent);

            given().contentType(ContentType.JSON)
                   .body(jsonPayload)
                   .when()
                   .post(DOCUMENTS_SERVICE_PATH)
                   .then()
                   .statusCode(200);

            given().when()
                   .get(DOCUMENTS_SERVICE_PATH + "/" + documentName)
                   .then()
                   .statusCode(200)
                   .body(equalTo(JsonHelper.toJson(documentContent)));
        });
    }

    /**
     * Verifies indirectly:<br>
     * - MultitenancyHarmoniaIT/tables/reader.table is created<br>
     * - MultitenancyHarmoniaIT/csvim/data.csvim is imported <br>
     * - MultitenancyHarmoniaIT/odata/readers.odata is configured <br>
     * - OData is working<br>
     * - default DB datasource is resolved correctly
     */
    private void verifyOData(DirigibleTestTenant tenant) {
        restAssuredExecutor.execute(tenant, () -> {
            verifyCSVIMIsImported();
            verifyAddingNewReader(tenant);
        });
    }

    private void verifyCSVIMIsImported() {
        given().header(HttpHeaders.ACCEPT, MediaType.APPLICATION_JSON_VALUE)
               .when()
               .get(READERS_ODATA_ENTITY_PATH)
               .then()
               .statusCode(200)
               .body("d.results", hasSize(2))
               .body("d.results[0].ReaderId", equalTo(1))
               .body("d.results[0].ReaderFirstName", equalTo("Ivan"))
               .body("d.results[0].ReaderLastName", equalTo("Ivanov"))
               .body("d.results[1].ReaderId", equalTo(2))
               .body("d.results[1].ReaderFirstName", equalTo("Maria"))
               .body("d.results[1].ReaderLastName", equalTo("Petrova"));
    }

    private void verifyAddingNewReader(DirigibleTestTenant tenant) {
        String firstName = "FirstName[" + tenant.getName() + "]";
        String lastName = "LastName[" + tenant.getName() + "]";
        String jsonPayload = String.format("""
                {
                    "ReaderId": 3,
                    "ReaderFirstName": "%s",
                    "ReaderLastName": "%s"
                }
                """, firstName, lastName);

        given().contentType(ContentType.JSON)
               .body(jsonPayload)
               .when()
               .post(READERS_ODATA_ENTITY_PATH)
               .then()
               .statusCode(201);

        given().header(HttpHeaders.ACCEPT, MediaType.APPLICATION_JSON_VALUE)
               .when()
               .get(READERS_ODATA_ENTITY_PATH)
               .then()
               .statusCode(200)
               .body("d.results", hasSize(3))
               .body("d.results[2].ReaderId", equalTo(3))
               .body("d.results[2].ReaderFirstName", equalTo(firstName))
               .body("d.results[2].ReaderLastName", equalTo(lastName));
    }

}
