/*
 * Copyright (c) 2010-2026 Eclipse Dirigible contributors
 *
 * All rights reserved. This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: Eclipse Dirigible contributors SPDX-License-Identifier: EPL-2.0
 */
package org.eclipse.dirigible.integration.tests.ui.tests;

import org.eclipse.dirigible.tests.framework.browser.Browser;
import org.eclipse.dirigible.tests.framework.browser.BrowserFactory;
import org.eclipse.dirigible.tests.framework.browser.HtmlElementType;
import org.eclipse.dirigible.tests.framework.tenant.DirigibleTestTenant;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.List;

/**
 * Harmonia+Java counterpart of {@link MultitenancyIT}. Verifies per-tenant isolation with the
 * entity application generated by {@code template-application-ui-harmonia-java} (Java REST +
 * Alpine/Harmonia SPA) instead of the AngularJS/TypeScript full-stack.
 * <p>
 * Building this uncovered - and the accompanying {@code JavaEntityManager} change closes - a real
 * gap: the generated <b>Java</b> DAOs were not multitenant-isolated. {@code data-store-java}'s
 * dynamic {@code SessionFactory} bound a single datasource, so every tenant's entity CRUD hit the
 * same schema (a second tenant saw the first tenant's rows). {@code JavaEntityManager} now applies
 * the same Hibernate multi-tenancy provider/resolver the TypeScript {@code DataStore} uses, so
 * Java-entity CRUD is isolated per tenant - which {@code verifyTestProjectWithMultipleTenants}
 * asserts here.
 */
public class MultitenancyHarmoniaIT extends MultitenancyUserInterfaceIntegrationTest {

    @Autowired
    private MultitenancyHarmoniaITTestProject testProject;

    @Autowired
    private BrowserFactory browserFactory;

    @Test
    void testOpenNotRegisteredTenant() {
        Browser browser = browserFactory.createBySubdomain("unregistered-tenant");
        browser.openPath("/index.html");
        browser.assertElementExistsByTypeAndText(HtmlElementType.FD_MESSAGE_PAGE_TITLE, "Page Not Found");
    }

    @Test
    void verifyTestProjectWithMultipleTenants() {
        List<DirigibleTestTenant> tenants = provisionTenants();

        testProject.test(tenants);
    }

    @Test
    void verifyTestProjectWithDefaultTenantOnly() {
        List<DirigibleTestTenant> tenants = List.of(DirigibleTestTenant.createDefaultTenant());

        testProject.test(tenants);
    }

}
