/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
export function getSources() {
	return [
		// Location: "gen/{{genFolderName}}/ui/extensions"
		{
			location: "/template-application-ui-angular/ui/extensions/menu-help.extension.template",
			action: "generate",
			rename: "gen/{{genFolderName}}/ui/extensions/menu-help.extension",
			engine: "velocity"
		},
		{
			location: "/template-application-ui-angular/ui/launchpad/menu-help.js",
			action: "copy",
			rename: "gen/{{genFolderName}}/ui/launchpad/menu-help.js"
		}
	];
};
