/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
export function getSources() {
	return [
		// Location: "gen/{{genFolderName}}/ui/extension-points"
		{
			location: "/template-application-ui-angular/ui/extension-points/dialog-window.extensionpoint.template",
			action: "generate",
			rename: "gen/{{genFolderName}}/ui/extension-points/dialog-window.extensionpoint",
			engine: "velocity"
		},
		{
			location: "/template-application-ui-angular/ui/extension-points/menu.extensionpoint.template",
			action: "generate",
			rename: "gen/{{genFolderName}}/ui/extension-points/menu.extensionpoint",
			engine: "velocity"
		},
		{
			location: "/template-application-ui-angular/ui/extension-points/settings.extensionpoint.template",
			action: "generate",
			rename: "gen/{{genFolderName}}/ui/extension-points/settings.extensionpoint",
			engine: "velocity"
		},
		{
			location: "/template-application-ui-angular/ui/extension-points/perspective.extensionpoint.template",
			action: "generate",
			rename: "gen/{{genFolderName}}/ui/extension-points/perspective.extensionpoint",
			engine: "velocity"
		},
		{
			location: "/template-application-ui-angular/ui/extension-points/shell.extensionpoint.template",
			action: "generate",
			rename: "gen/{{genFolderName}}/ui/extension-points/shell.extensionpoint",
			engine: "velocity"
		},
		{
			location: "/template-application-ui-angular/ui/extension-points/subview.extensionpoint.template",
			action: "generate",
			rename: "gen/{{genFolderName}}/ui/extension-points/subview.extensionpoint",
			engine: "velocity"
		},
		{
			location: "/template-application-ui-angular/ui/extension-points/view.extensionpoint.template",
			action: "generate",
			rename: "gen/{{genFolderName}}/ui/extension-points/view.extensionpoint",
			engine: "velocity"
		},
		{
			location: "/template-application-ui-angular/ui/extension-points/tile.extensionpoint.template",
			action: "generate",
			rename: "gen/{{genFolderName}}/ui/extension-points/tile.extensionpoint",
			engine: "velocity"
		}
	];
};
