/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
import * as extensionPointsTemplate from "template-application-ui-angular/template/ui/extensionPoints";
import * as extensionsTemplate from "template-application-ui-angular/template/ui/extensions";
import * as listTemplate from "template-application-ui-angular/template/ui/list";
import * as manageTemplate from "template-application-ui-angular/template/ui/manage";
import * as masterDetailsListTemplate from "template-application-ui-angular/template/ui/masterDetailsList";
import * as masterDetailsManageTemplate from "template-application-ui-angular/template/ui/masterDetailsManage";
import * as reportTemplate from "template-application-ui-angular/template/ui/report";
import * as reportChartTemplate from "template-application-ui-angular/template/ui/reportChart";
import * as reportTableTemplate from "template-application-ui-angular/template/ui/reportTable";
// import * as perspective from "template-application-ui-angular/template/ui/perspective";
import * as launchpad from "template-application-ui-angular/template/ui/launchpad";
// import * as tiles from "template-application-ui-angular/template/ui/tiles";
// import * as menu from "template-application-ui-angular/template/ui/menu";

export function getSources(parameters) {
    return [
        ...extensionPointsTemplate.getSources(parameters),
        ...extensionsTemplate.getSources(parameters),
        ...launchpad.getSources(parameters),
        ...listTemplate.getSources(parameters),
        ...manageTemplate.getSources(parameters),
        ...masterDetailsListTemplate.getSources(parameters),
        ...masterDetailsManageTemplate.getSources(parameters),
        ...reportTemplate.getSources(parameters),
        ...reportChartTemplate.getSources(parameters),
        ...reportTableTemplate.getSources(parameters),
        //...perspective.getSources(parameters),
        //...tiles.getSources(parameters),
        //...menu.getSources(parameters)
    ];
};
