name: Build

on:
  push:
    branches: 
      - main
      - master
      - build-action-improvements

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - name: Set up JDK 13
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '13'
        architecture: x64
    - name: Maven Build
      # run: mvn clean install -Dmaven.javadoc.skip=false
      run:  mvn -T 1C clean install -Dmaven.test.skip=true -DskipTests -Dmaven.javadoc.skip=true -Dlicense.skip=true

    - uses: actions/upload-artifact@v3
      with:
        name: releng-folder
        path: releng/

  docker-1:
    needs: build
    name: Docker - Anonymous
    uses: ./.github/workflows/push-docker.yml
    with:
      location: releng/anonymous-all
      baseImageRepository: dirigiblelabs/dirigible-base-platform-anonymous
      imageRepository: dirigiblelabs/dirigible-anonymous
    secrets: inherit

  docker-2:
    needs: build
    name: Docker - Anonymous - Runtime
    uses: ./.github/workflows/push-docker.yml
    with:
      location: releng/anonymous-runtime
      baseImageRepository: dirigiblelabs/dirigible-base-platform-runtime-anonymous
      imageRepository: dirigiblelabs/dirigible-runtime-anonymous
    secrets: inherit

  docker-3:
    needs: build
    name: Docker - OpenShift
    uses: ./.github/workflows/push-docker.yml
    with:
      location: releng/openshift-all
      baseImageRepository: dirigiblelabs/dirigible-base-platform-openshift
      imageRepository: dirigiblelabs/dirigible-openshift
    secrets: inherit

  docker-4:
    needs: build
    name: Docker - SAP Cloud Foundry
    uses: ./.github/workflows/push-docker.yml
    with:
      location: releng/sap-cf-all
      baseImageRepository: dirigiblelabs/dirigible-base-platform-sap-cf
      imageRepository: dirigiblelabs/dirigible-sap-cf
    secrets: inherit

  docker-5:
    needs: build
    name: Docker - SAP Cloud Foundry - Runtime
    uses: ./.github/workflows/push-docker.yml
    with:
      location: releng/sap-cf-runtime
      baseImageRepository: dirigiblelabs/dirigible-base-platform-sap-cf-runtime
      imageRepository: dirigiblelabs/dirigible-sap-cf-runtime
    secrets: inherit

  docker-6:
    needs: build
    name: Docker - SAP Kyma
    uses: ./.github/workflows/push-docker.yml
    with:
      location: releng/sap-kyma-all
      baseImageRepository: dirigiblelabs/dirigible-base-platform-sap-kyma
      imageRepository: dirigiblelabs/dirigible-sap-kyma
    secrets: inherit

  docker-7:
    needs: build
    name: Docker - SAP Kyma - Runtime
    uses: ./.github/workflows/push-docker.yml
    with:
      location: releng/sap-kyma-runtime
      baseImageRepository: dirigiblelabs/dirigible-base-platform-sap-kyma-runtime
      imageRepository: dirigiblelabs/dirigible-sap-kyma-runtime
    secrets: inherit

  docker-8:
    needs: build
    name: Docker - Dirigible
    uses: ./.github/workflows/push-docker.yml
    with:
      location: releng/server-all
      baseImageRepository: dirigiblelabs/dirigible-base-platform
      imageRepository: dirigiblelabs/dirigible-all
    secrets: inherit

  docker-9:
    needs: build
    name: Docker - Dirigible - Runtime
    uses: ./.github/workflows/push-docker.yml
    with:
      location: releng/server-runtime
      baseImageRepository: dirigiblelabs/dirigible-base-platform-runtime
      imageRepository: dirigiblelabs/dirigible-runtime
    secrets: inherit

  docker-10:
    needs: build
    name: Docker - Dirigible - Trial
    uses: ./.github/workflows/push-docker.yml
    with:
      location: releng/trial-all
      baseImageRepository: dirigiblelabs/dirigible-base-platform-trial
      imageRepository: dirigiblelabs/dirigible-trial
    secrets: inherit

  docker-11:
    needs: build
    name: Docker - Dirigible - Keycloak
    uses: ./.github/workflows/push-docker.yml
    with:
      location: releng/server-keycloak-all
      baseImageRepository: dirigiblelabs/dirigible-base-platform-keycloak
      imageRepository: dirigiblelabs/dirigible-keycloak
    secrets: inherit

  docker-12:
    needs: build
    name: Docker - Dirigible - Keycloak - Runtime
    uses: ./.github/workflows/push-docker.yml
    with:
      location: releng/server-runtime-keycloak
      baseImageRepository: dirigiblelabs/dirigible-base-platform-runtime-keycloak
      imageRepository: dirigiblelabs/dirigible-runtime-keycloak
    secrets: inherit

    # - uses: buildpacks/github-actions/setup-pack@v4.1.0
    # - name: Eclipse Dirigible Buildpack
    #   run: |
    #     cd releng/buildpacks/server/
    #     docker build --load -t dirigiblelabs/buildpacks-stack-base-dirigible . --target base
    #     docker push dirigiblelabs/buildpacks-stack-base-dirigible
    #     docker build --load -t dirigiblelabs/buildpacks-stack-run-dirigible . --target run
    #     docker push dirigiblelabs/buildpacks-stack-run-dirigible
    #     docker build --load -t dirigiblelabs/buildpacks-stack-build-dirigible . --target build
    #     docker push dirigiblelabs/buildpacks-stack-build-dirigible
    #     cd buildpack/
    #     find *.toml -type f -exec sed -i ''s/#{DirigibleVersion}#/latest/g'' {} \;
    #     pack buildpack package dirigiblelabs/buildpacks-dirigible --config ./package.toml
    #     docker push dirigiblelabs/buildpacks-dirigible
    #     pack builder create dirigiblelabs/buildpacks-builder-dirigible --config ./builder.toml
    #     docker push dirigiblelabs/buildpacks-builder-dirigible
    #     cd ../../../../
    # - name: Eclipse Dirigible Kyma Buildpack
    #   run: |
    #     cd releng/buildpacks/sap-kyma/
    #     docker build --load -t dirigiblelabs/buildpacks-stack-base-dirigible-kyma . --target base
    #     docker push dirigiblelabs/buildpacks-stack-base-dirigible-kyma
    #     docker build --load -t dirigiblelabs/buildpacks-stack-run-dirigible-kyma . --target run
    #     docker push dirigiblelabs/buildpacks-stack-run-dirigible-kyma
    #     docker build --load -t dirigiblelabs/buildpacks-stack-build-dirigible-kyma . --target build
    #     docker push dirigiblelabs/buildpacks-stack-build-dirigible-kyma
    #     cd buildpack/
    #     find *.toml -type f -exec sed -i ''s/#{DirigibleVersion}#/latest/g'' {} \;
    #     pack buildpack package dirigiblelabs/buildpacks-dirigible-kyma --config ./package.toml
    #     docker push dirigiblelabs/buildpacks-dirigible-kyma
    #     pack builder create dirigiblelabs/buildpacks-builder-dirigible-kyma --config ./builder.toml
    #     docker push dirigiblelabs/buildpacks-builder-dirigible-kyma
    #     cd ../../../../
    # - name: Eclipse Dirigible Cloud Foundry Buildpack
    #   run: |
    #     cd releng/buildpacks/sap-cf/
    #     docker build --load -t dirigiblelabs/buildpacks-stack-base-dirigible-cf . --target base
    #     docker push dirigiblelabs/buildpacks-stack-base-dirigible-cf
    #     docker build --load -t dirigiblelabs/buildpacks-stack-run-dirigible-cf . --target run
    #     docker push dirigiblelabs/buildpacks-stack-run-dirigible-cf
    #     docker build --load -t dirigiblelabs/buildpacks-stack-build-dirigible-cf . --target build
    #     docker push dirigiblelabs/buildpacks-stack-build-dirigible-cf
    #     cd buildpack/
    #     find *.toml -type f -exec sed -i ''s/#{DirigibleVersion}#/latest/g'' {} \;
    #     pack buildpack package dirigiblelabs/buildpacks-dirigible-cf --config ./package.toml
    #     docker push dirigiblelabs/buildpacks-dirigible-cf
    #     pack builder create dirigiblelabs/buildpacks-builder-dirigible-cf --config ./builder.toml
    #     docker push dirigiblelabs/buildpacks-builder-dirigible-cf
    #     cd ../../../../

  clean-up:
    name: Clean-up
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs:
      - build
      - docker-1
      - docker-2
      - docker-3
      - docker-4
      - docker-5
      - docker-6
      - docker-7
      - docker-8
      - docker-9
      - docker-10
      - docker-11
      - docker-12
    steps:
    - run: echo Do nothing
#     - uses: geekyeggo/delete-artifact@v2
#       with:
#           name: releng-folder
#           failOnError: false
